#ifndef T48_TRANSLATE_ID_DIFINE_H_
#define T48_TRANSLATE_ID_DIFINE_H_


/*****************************************************************
******************************通用(common)**************************
*******************************************************************/
#define COMM_OPERATE_SOFT_SWITCH                    "Switch"
#define COMM_OPERATE_CANCEL                         "Cancel"
#define COMM_OPERATE_OK                             "OK"
#define COMM_OPERATE_DELETE                         "Delete"
#define COMM_OPERATE_CONNECT                        "Connect"

#define COMM_LABEL_WEB_ACCESS_FAILED                "Web access password is wrong !"
#define COMM_LABEL_PASSWORD                         "Password"
#define COMM_LABEL_FIRMWARE                         "Firmware"

#define COMM_TIP_MORE                               "More"
#define COMM_TIP_PASSWORD_IS_WRONG                  "Password is wrong!"

#define COMM_TITLE_ENTER_PASSWORD                    "Enter Password"

#define COMM_TIP_CURRENT_PIN_INCORRECT              "Current PIN is incorrect!"

#define COMM_SELECT_TITLE_SELECT_ALL                "Select All"

#define COMM_LABEL_DSSKEY                           "Dss Key"
/********************************************************************
*****************************TalkUI*******************************
********************************************************************/
// softkey
#define TALK_OPERATE_SOFT_PICKUP                    "Pickup"
#define TALK_OPERATE_SOFT_DIAL                      "Dial"
#define TALK_OPERATE_SOFT_NEWCALL                   "New Call"
#define TALK_OPERATE_SOFT_ANSWER                    "Answer"
#define TALK_OPERATE_SOFT_REJECT                    "Reject"
#define TALK_OPERATE_SOFT_BARGEIN                   "Barge In"
#define TALK_OPERATE_SOFT_RESUME                    "Resume"
#define TALK_OPERATE_SOFT_PRIHOLD                   "PriHold"
#define TALK_OPERATE_SOFT_LINE                      "Line"
#define TALK_OPERATE_SOFT_SEND                      "Send"
#define TALK_OPERATE_SOFT_REDIAL                    "Redial"
#define TALK_OPERATE_SOFT_ENDCALL                   "End Call"
#define TALK_OPERATE_SOFT_IGNORE                    "Silence"
#define TALK_OPERATE_SOFT_FORWARD                   "Forward"
#define TALK_OPERATE_SOFT_SWAP                      "Swap"
#define TALK_OPERATE_SOFT_HOLD                      "Hold"
#define TALK_OPERATE_SOFT_MUTE_VOICE                "Mute"
#define TALK_OPERATE_SOFT_TRANSFER                  "Transfer"
#define TALK_OPERATE_SOFT_CONFERENCE                "Conference"
#define TALK_OPERATE_SOFT_SPLIT                     "Split"
#define TALK_OPERATE_SOFT_REOMVE                    "Remove"
#define TALK_OPERATE_SOFT_OPENHISTORY               "History"
#define TALK_OPERATE_SOFT_OPENDIRECTORY             "Directory"
#define TALK_OPERATE_SOFT_AUTOREDIAL                "OK"
#define TALK_OPERATE_SOFT_PARK                      "Park"
#define TALK_OPERATE_SOFT_GROUP_PARK                "GPark"
#define TALK_OPERATE_SOFT_RETRIEVE_PARK             "Retrieve"
#define TALK_OPERATE_SOFT_ACD_CALL_INFO             "CallInfo"
#define TALK_OPERATE_SOFT_ACD_DISPCODE              "DispCode"
#define TALK_OPERATE_SOFT_ACD_TRACE                 "Trace"
#define TALK_OPERATE_SOFT_ACD_EMERGESCAL            "Emergency"
#define TALK_OPERATE_SOFT_DPICKUP                   "DPickup"
#define TALK_OPERATE_SOFT_GPICKUP                   "GPickup"
#define TALK_OPERATE_SOFT_EXIT                      "Exit"

// 全局的提示语
#define TALK_NOTE_NETWORK_UNAVAILABLE                    "Network Unavailable"
#define TALK_TIP_INVALID_CODEC_TOCONF                "The audio codecs is different, can’t set up a conference!"
#define TALK_TIP_NOT_AVALIABLE_G722_SESSION_TOCONF "g722 codec is not avaliable in four ways conference!"
#define TALK_TIP_NOT_AVALIABLE_SRTP_SESSION_TOCONF "srtp is not avaliable in four ways conference!"
#define TALK_TIP_ARE_YOU_SURE_TO_REMOVE "Are you sure to remove "

// Talk界面常用的一些翻译
#define TALK_STATUS_MUTE                                "Mute"
#define TALK_STATUS_FAR_MUTE                            "Far Mute"
#define TALK_STATUS_HELD                                "Held"
#define TALK_STATUS_HOLD                                "Hold"
#define TALK_STATUS_PARKED                              "Parked"
#define TALK_STATUS_TRANSFER                            "Transfer"
#define TALK_STATUS_BETRANSFERRED                       "Betransferred"
#define TALK_STATUS_TRANSFERED                          "Transfered"
#define TALK_STATUS_TRANSING                            "Transferring"
#define TALK_STATUS_TRANSFER_FAIL                       "Transfer Failed"
#define TALK_STATUS_TALKING                             "Talking"
#define TALK_STATUS_CALLFAIL                            "Call Fail"
#define TALK_STATUS_CALLFINISH                          "Call Finish"
#define TALK_STATUS_CONFERENCE                          "Conference"
#define TALK_STATUS_CALLING                             "Outgoing Call"
#define TALK_STATUS_RING                                "Incoming Call"

// Park失败的提示
#define TALK_LABEL_PARK_FAILED                          "Park Failed"
#define TALK_LABEL_PARK_BAD_REQUEST                     "Bad Request"
#define TALK_LABEL_PARK_FORBIDDEN                       "Forbidden"
#define TALK_LABEL_PARK_TIME_OUT                        "Time out"
#define TALK_LABEL_PARK_UNKNOW                          "Unknown"
#define TALK_LABEL_PARK_AUTH_ERROR                      "auth error"
#define TALK_LABEL_PARK_SERVER_ERROR                    "server error"

// CALLINFO 界面
#define TALK_TITLE_DLG_CALLINFO                     "Call Infomation"
#define TALK_LABEL_DLG_CALLINFO_WAIT_TIME           "Wait Time"
#define TALK_LABEL_DLG_CALLINFO_CC_NAME             "CC Name"
#define TALK_LABEL_DLG_CALLINFO_CC_UID              "CC UID"
#define TALK_LABEL_DLG_CALLINFO_QUEUE               "Queue"
#define TALK_LABEL_DLG_CALLINFO_CALLS_LONGEST       "Calls Longest"

// Pickup界面
#define TALK_TITLE_DLG_PICKUP                       "Calls for Pickup"
#define TALK_LABEL_DLG_PICKUP_NONE                  "None"      // Pick界面没有Menu时候的容错处理

// SCAMENU界面
#define TALK_TITLE_DLG_SCAMENU                      "Shared Calls"
#define TALK_STATUS_DLG_SCAMENU_ALERTING            "SCA Alerting"
#define TALK_STATUS_DLG_SCAMENU_ACTIVE              "SCA Active"
#define TALK_STATUS_DLG_SCAMENU_HELD                "SCA Held"
#define TALK_STATUS_DLG_SCAMENU_HELD_PRIVATE        "SCA Held Private"
#define TALK_STATUS_DLG_SCAMENU_BRIDGE_ACTIVE       "SCA Bridge Active"
#define TALK_STATUS_DLG_SCAMENU_BRIDGE_HELD         "SCA Bridge Held"
#define TALK_STATUS_DLG_SCAMENU_UNKNOWN             "SCA Unknown"
#define TALK_LABEL_DLG_SCAMENU_DISPLAYNAME              "Unknown"   // 账号显示名获取不到时候的容错方案

// 会议界面
#define TALK_TITLE_DLG_CONFERENCE                   "Conference"

// ConnectUI
#define TALK_TITLE_DLG_CONNECT_TRAN                 "Transferring"
#define TALK_TITLE_DLG_CONNECT_CALLING              "Calling"

// Dialing界面
#define TALK_TITLE_DLG_DIAL_FORWARD                 "Forward to"
#define TALK_TITLE_DLG_DIAL_TRAN                    "Transfer to"
#define TALK_TITLE_DLG_DIAL_CONFERENCE              "Conference with"
#define TALK_TITLE_DLG_DIAL_PARK                    "Park"
#define TALK_TITLE_DLG_DIAL_RETRIEVE_PARK           "Retrieve Park"
#define TALK_TITLE_DLG_DIAL_CALL_PICK               "Call Pickup"
#define TALK_LABEL_DLG_DIAL_DPICKUP                 "DPickup"
#define TALK_LABEL_DLG_DIAL_GPICKUP                 "GPickup"
#define TALK_LABEL_DLG_DIAL_BLIND_TRAN              "Transfer"
#define TALK_LABEL_DLG_DIAL_SEND                    "Send"
#define TALK_LABEL_DLG_DIAL_CONFERENC               "Conference"
#define TALK_LABEL_DLG_DIAL_RING_FORWARD            "Forward"
#define TALK_LABEL_DLG_DIAL_RETRIEVE_CALLPARK       "Retrieve"
#define TALK_LABEL_DLG_DIAL_CALL_PARK               "Park"

// finishUI界面
#define TALK_TITLE_DLG_FINISH_FAIL                  "Call Fail"
#define TALK_TITLE_DLG_FINISH_FINISH                "Call Finish"
#define TALK_TIP_DLG_FINISH_REDIAL_TIME             "Redial times"
#define TALK_TIP_DLG_FINISH_INTERVAL                "Interval"
#define TALK_TIP_DLG_FINISH_ERROR_INVALID_ACCOUNT   "Invalid account"
#define TALK_TIP_DLG_FINISH_TALK_ERROR1             "Share line unavailable"
#define TALK_LABEL_DLG_FINISH_AUTO_REDIAL           "Auto Redial?"

// ParkNotify界面
#define TALK_TITLE_DLG_PARK_NOTIFY                  "Call Park"

// 来电界面
#define TALK_TITLE_DLG_RING_RECALL                  "Recall"
#define TALK_TITLE_DLG_RING_RINGING                 "Ringing"
#define TALK_LABEL_DLG_RING_RECALL                  "Recall"
#define TALK_LABEL_DLG_RING_TALK_FROM               "Talk From"
#define TALK_LABEL_DLG_RING_VIA                     "Via"

// 通话界面
#define TALK_TITLE_DLG_TALKING_TALKING              "Talking"
#define TALK_TITLE_DLG_TALKING_TRANSFERRING         "Transferring"
#define TALK_TITLE_DLG_TALKING_TRANSFERRED          "Transferred"
#define TALK_TITLE_DLG_TALKING_BETRANSFREED         "Betransferred"

// FAVORITE弹出框的选项
#define FAVORITE_TITLE_FAVORITE                         "Directories"
#define FAVORITE_LABEL_SHOW_NAME_LOCAL_CONTACT          "Local Contacts"
#define FAVORITE_LABEL_SHOW_NAME_LOCAL_CALLLOG          "Local Calllog"
#define FAVORITE_LABEL_SHOW_NAME_REMOTE_CONTACT         "Remote Contacts"
#define FAVORITE_LABEL_SHOW_NAME_LDAP_CONTACT           "LDAP"
#define FAVORITE_LABEL_SHOW_NAME_BST_CONTACT            "Broadsoft Contacts"
#define FAVORITE_LABEL_SHOW_NAME_BST_CALLLOG            "Broadsoft Calllog"

// ACD Queue Status
#define ACD_LABEL_QUEUE_STATUS_EMPTY                    "empty"
#define ACD_LABEL_QUEUE_STATUS_QING                     "q'ing"
#define ACD_LABEL_QUEUE_STATUS_ALERT                    "ALERT"


/********************************************************************
*****************************SettingUI*******************************
********************************************************************/
//下拉框
#define SET_OPTION_DISABLED "Disabled"
#define SET_OPTION_ENABLED "Enabled"
#define SET_OPTION_AVAILABLE "Available"
#define SET_OPTION_UNAVAILABLE "Unavailable"
#define SET_OPTION_WRAP_UP "Wrap-Up"
#define SET_OPTION_SIGNIN "SignIn"
#define SET_OPTION_SIGN_OUT "SignOut"
#define SET_OPTION_ON "On"
#define SET_OPTION_OFF "Off"
#define SET_OPTION_TIME_FORMATE_24_HOUR "24 Hour"
#define SET_OPTION_TIME_FORMATE_12_HOUR "12 Hour"
#define SET_OPTION_DATE_FORMATE_WWW_MMM_DD "WWW MMM DD"
#define SET_OPTION_DATE_FORMATE_DD_MMM_YY "DD-MMM-YY"
#define SET_OPTION_DATE_FORMATE_YYYY_MM_DD "YYYY-MM-DD"
#define SET_OPTION_DATE_FORMATE_DD_MM_YYYY "DD/MM/YYYY"
#define SET_OPTION_DATE_FORMATE_MM_DD_YY "MM/DD/YY"
#define SET_OPTION_DATE_FORMATE_DD_MMM_YYYY "DD MMM YYYY"
#define SET_OPTION_DATE_FORMATE_WWW_DD_MMM "WWW DD MMM"
#define SET_OPTION_SNTP "SNTP"
#define SET_OPTION_MANUAL "Manual"
#define SET_OPTION_AUTOMATIC "Automatic"
#define SET_OPTION_NO_ACCOUNT "No Account"
#define SET_OPTION_NA "N/A"
#define SET_OPTION_SPEED_DIAL "Speed Dial"
#define SET_OPTION_BLF "BLF"
#define SET_OPTION_KEY_EVENT "Key Event"
#define SET_OPTION_INTERCOM "Intercom"
#define SET_OPTION_BLF_LIST "BLF List"
#define SET_OPTION_RETRIEVE "Retrieve"
#define SET_OPTION_LABEL_URL "URL"
#define SET_OPTION_URL_RECORD "URL Record"
#define SET_OPTION_ACD "ACD"
#define SET_OPTION_MEET_ME "Meet-me"
#define SET_OPTION_HOTELING "Hoteling"
#define SET_OPTION_ACD_TRACE "ACD Trace"
#define SET_OPTION_DISPCODE "DispCode"
#define SET_OPTION_EMERGENCY "Emergency"
#define SET_OPTION_UC_FAVORITE "UC Favorite"
#define SET_OPTION_BSFT_GROUP "BroadSoft Group"
#define SET_OPTION_BUDDIES "Buddies"
#define SET_OPTION_MY_STATUS "My Status"
#define SET_OPTION_CALL_PARK "Call Park"
#define SET_OPTION_CALL_RETURN "Call Return"
#define SET_OPTION_CONFERENCE "Conference"
#define SET_OPTION_DND "DND"
#define SET_OPTION_DTMF "DTMF"
#define SET_OPTION_DIRECTORIES "Directories"
#define SET_OPTION_FORWARD "Forward"
#define SET_OPTION_GROUP_LISTENING "Group Listening"
#define SET_OPTION_GROUP_PICK_UP "Group Pick Up"
#define SET_OPTION_HOLD "Hold"
#define SET_OPTION_LDAP "LDAP"
#define SET_OPTION_LOCAL_GROUP "Local Group"
#define SET_OPTION_NETWORK_FAVORITE "Network Favorite"
#define SET_OPTION_PAGING "Paging"
#define SET_OPTION_PICK_UP "Pick Up"
#define SET_OPTION_PREFIX "Prefix"
#define SET_OPTION_PRIVATE_HOLD "Private Hold"
#define SET_OPTION_PUBLIC_HOLD "Public Hold"
#define SET_OPTION_RECORD "Record"
#define SET_OPTION_REDIAL "Redial"
#define SET_OPTION_SMS "SMS"
#define SET_OPTION_TRANSFER "Transfer"
#define SET_OPTION_VOICE_MAIL "Voice Mail"
#define SET_OPTION_XML_BROWSER "XML Browser"
#define SET_OPTION_XML_GROUP "XML Group"
#define SET_OPTION_ZERO_SP_TOUCH "Zero-SP-Touch"
#define SET_OPTION_KEYPAD_LOCK "Keypad Lock"
#define SET_OPTION_TITLE_HOT_DESKING "Hot Desking" //MULTI
#define SET_OPTION_AUTO "Auto"
#define SET_OPTION_ALL_XML_GROUP "All XML Group"
#define SET_OPTION_ALL_BSFT_GROUP "All Broadsoft Group"
#define SET_OPTION_ALL_KEY "All Key"
#define SET_OPTION_FUN_KEY "Fun Key"
#define SET_OPTION_MENU_KEY "Menu Key"
#define SET_OPTION_EAP_MD5 "EAP-MD5"
#define SET_OPTION_EAP_TLS "EAP-TLS"
#define SET_OPTION_PEAP_MSCHAPV2 "PEAP-MSCHAPV2"
#define SET_OPTION_EAP_TTLS_EAP_MSCHAPv2 "EAP-TTLS/EAP-MSCHAPv2"
#define SET_OPTION_FULL_RESET "Full Reset"
#define SET_OPTION_CONFIGURATION_RESET "Configuration Reset"
#define SET_OPTION_USERDATA_RESET "Userdata Reset"
#define SET_OPTION_IPV4_AND_IPV6 "IPV4 & IPV6"
#define SET_OPTION_IPv4_AND_IPv6 "IPv4 & IPv6"
#define SET_OPTION_LOW "Low"
#define SET_OPTION_ALWAYS_ON "Always On"
#define SET_OPTION_BACKLIGHT_TIME_1_MIN "1 min"
#define SET_OPTION_BACKLIGHT_TIME_2_MIN "2 min"
#define SET_OPTION_BACKLIGHT_TIME_5_MIN "5 min"
#define SET_OPTION_BACKLIGHT_TIME_10_MIN "10 min"
#define SET_OPTION_BACKLIGHT_TIME_30_MIN "30 min"
#define SET_OPTION_KEY_POUND "Key #"
#define SET_OPTION_KEY_STAR "Key *"
#define SET_OPTION_DHCP "DHCP"
#define SET_OPTION_PPPOE "PPPoE"
#define SET_OPTION_STATIC "Static"
#define SET_OPTION_STATIC_IP "Static IP"
#define SET_OPTION_INVALID_WAN_TYPE "Invalid WAN type"
#define SET_OPTION_UNKNOWN "Unknown"
#define SET_OPTION_REGISTERING "Registering"
#define SET_OPTION_REGISTERED "Registered"
#define SET_OPTION_REGISTER_FAIL "Register fail"
#define SET_OPTION_REGISTER_FAILED "Register Failed"
#define SET_OPTION_UNREGISTERED "Unregistered"
#define SET_OPTION_SYSTEM_DEFAULT_ACCOUNT "System default account"
#define SET_OPTION_INEXISTENCE "Inexitstence"
#define SET_OPTION_UNREGISTERING "Unregistering"
#define SET_OPTION_BRIDGE "Bridge"
#define SET_OPTION_FWD_INTERNATIONAL "FWD International"

//配置项标签
#define SET_LABEL_ACTIVATION "Activation"
#define SET_LABEL_LABEL "Label"
#define SET_LABEL_DISPLAY_NAME "Display Name"
#define SET_LABEL_REGISTER_NAME "Register Name"
#define SET_LABEL_USER_NAME "User Name"
#define SET_LABEL_SIP_SERVER1 "SIP Server1"
#define SET_LABEL_SIP_SERVER2 "SIP Server2"
#define SET_LABEL_OUTBOUND_STATUS "Outbound Status"
#define SET_LABEL_OUTBOUND_PROXY "Outbound Proxy"
#define SET_LABEL_STUN_STATUS "STUN Status"
#define SET_LABEL_STUN_SERVER "STUN Server"
#define SET_LABEL_ENTER_CODE "Enter Code"
#define SET_LABEL_ENTER_NUMBER "Enter Number"
#define SET_LABEL_LOGIN_AS "Login As"
#define SET_LABEL_ALWAYS_FORWARD "Always Forward"
#define SET_LABEL_BUSY_FORWARD "Busy Forward"
#define SET_LABEL_NO_ANSWER_FORWARD "No Answer Forward"
#define SET_LABEL_FORWARD_TO "Forward To"
#define SET_LABEL_ON_CODE "On Code"
#define SET_LABEL_OFF_CODE "Off Code"
#define SET_LABEL_AFTER_RING_TIMES "After Ring Times"
#define SET_LABEL_NAME "Name"
#define SET_LABEL_PHONE_NUMBER "Phone Number"
#define SET_LABEL_ENABLE_THIS_LOCATION "Enable this Location"
#define SET_LABEL_OUTBONT_ALTERNATE_PHONE_NUMBER "Outbound Alternate Phone Number"
#define SET_LABEL_ENABLE_DIVERSION_INHIBITOR "Enable Diversion Inhibitor"
#define SET_LABEL_REQUIRE_ANSWER_CONFIRMATION "Require Answer Confirmation"
#define SET_LABEL_USE_BROADWORKS_CALL_CONTROL "Use BroadWorks-based Call Control"
#define SET_LABEL_USER_TYPE "User Type"
#define SET_LABEL_OPTION_LINE "Line"
#define SET_LABEL_AUTO_REDIAL "Auto Redial"
#define SET_LABEL_REDIAL_INTERVAL "Redial Interval"
#define SET_LABEL_REDIAL_TIMES "Redial Time"
#define SET_LABEL_DEVICE_NAME "Device Name"
#define SET_LABEL_MAC_ADDRESS "MAC Address"
#define SET_LABEL_AUTO_CONNECT "AutoConnect"
#define SET_LABEL_MY_DEVICE_INFOMATION "My Device Information"
#define SET_LABEL_BLUETOOTH "Bluetooth"
#define SET_LABEL_SCANING_BLUETOOTH_DEVICES "Scaning bluetooth devices..."
#define SET_LABEL_BLUETOOTH_DEVICES "bluetooth devices:"
#define SET_LABEL_BLUETOOTH_DEVICES_CONNECTING_WITH "bluetooth devices(Connecting with "

#define SET_LABEL_CALL_FORWARDING "CallForwarding"
#define SET_LABEL_CALL_FORWARD "Call Forward"
#define SET_LABEL_DO_NOT_DISTURB "Do Not Disturb"
#define SET_LABEL_ANYWHERE "Anywhere"
#define SET_LABEL_TITLE_REMOTE_OFFICE "Remote Office" //MULTI
#define SET_LABEL_TITLE_HIDE_NUMBER "Hide Number"
#define SET_LABEL_TITLE_ANONYMOUS_REJECTION "Anonymous Rejection"
#define SET_LABEL_SIMULTANEOUS_RING_PERSONAL "Simultaneous Ring Personal"
#define SET_LABEL_INITIAL_ACD_STATE "Initial ACD State"
#define SET_LABEL_CALL_WAITING "Call Waiting"
#define SET_LABEL_PLAY_TONE "Play Tone"
#define SET_LABEL_CUSTOM_FORWARD "Custom Forward"
#define SET_LABEL_DATE_FORMATE "Date Format"
#define SET_LABEL_TIME_FORMATE "Time Format"
#define SET_LABEL_TYPE "Type"
#define SET_LABEL_DATE "Date"
#define SET_LABEL_TIME "Time"
#define SET_LABEL_TIME_ZONE "Time Zone"
#define SET_LABEL_NTP_SERVER1 "NTP Server1"
#define SET_LABEL_NTP_SERVER2 "NTP Server2"
#define SET_LABEL_DAYLIGHT_SAVINE "Daylight Saving"
#define SET_LABEL_DEFAULT_ACCOUNT "Default Account"
#define SET_LABEL_DHCP_TIME "DHCP Time"
#define SET_LABEL_TITLE_STATUS "Status" //MULTI
#define SET_LABEL_USER_ID "User ID"
#define SET_LABEL_AUTO_LOGIN "Auto-login"
#define SET_LABEL_USER_HOST "User Host"
#define SET_LABEL_INTERCOM_ALLOW "Intercom Allow"
#define SET_LABEL_INTERCOM_MUTE "Intercom Mute"
#define SET_LABEL_INTERCOM_TONE "Intercom Tone"
#define SET_LABEL_INTERCOM_BARGE "Intercom Barge"
#define SET_LABEL_WAN_TYPE "WAN Type"
#define SET_LABEL_WAN_IP "WAN IP"
#define SET_LABEL_MASK "MASK"
#define SET_LABEL_GATEWAY "Gateway"
#define SET_LABEL_PRI_DNS "Pri.DNS"
#define SET_LABEL_SEC_DNS "Sec.DNS"
#define SET_LABEL_KEYPAD_LOCK_ENABLE "Keypad Lock Enable"
#define SET_LABEL_KEYPAD_LOCK_TYPE "Keypad Lock Type"
#define SET_LABEL_WAN_PORT_VLAN "WAN Port VLAN"
#define SET_LABEL_VID_NUMBER "VID Number"
#define SET_LABEL_PRIORITY "Priority"
#define SET_LABEL_VPN_ACTIVE "VPN Active"
#define SET_LABEL_SERVER_STATUS "Server Status"
#define SET_LABEL_START_IP "Start IP"
#define SET_LABEL_END_IP "End IP"
#define SET_LABEL_IP "IP"
#define SET_LABEL_SUB_MASK "Subnet Mask"
#define SET_LABEL_DHCP_SERVER "DHCP Server"
#define SET_LABEL_HTTP "Http"
#define SET_LABEL_HTTP_PORT "Http Port"
#define SET_LABEL_HTTPS "Https"
#define SET_LABEL_HTTPS_PORT "Https Port"
#define SET_LABEL_8021X_MODE "802.1x Mode"
#define SET_LABEL_IDENTIFY "Identity"
#define SET_LABEL_RESET_OPTION "Reset Option"
#define SET_LABEL_CURRENT_PASSWORD "Current Password"
#define SET_LABEL_NEW_PASSWORD "New Password"
#define SET_LABEL_CONFIRM_PASSWORD "Confirm Password"
#define SET_LABEL_ANSWER_COMFMATION "Answer Comfimation"
#define SET_LABEL_OPTION_IPV4 "IPV4" //MULTI
#define SET_LABEL_OPTION_IPV6 "IPV6" //MULTI
#define SET_LABEL_MAC "MAC"
#define SET_LABEL_CURRENT_PIN "Current PIN"
#define SET_LABEL_NEW_PIN "New PIN"
#define SET_LABEL_CONFIRM_PIN "Confirm PIN"
#define SET_LABEL_SEND_ANONYMOUS "Local Anonymous"
#define SET_LABEL_ANONYMOUS_CODE "Send Anonymous Code"
#define SET_LABEL_ANONYMOUS_REJECT "Anonymous Reject"
#define SET_LABEL_CALL_COMPLETION "Call Completion"
#define SET_LABEL_ACTIVE_LEVEL "Active Level"
#define SET_LABEL_INACTIVE_LEVEL "Inactive Level"
#define SET_LABEL_BACKLIGHT_ACTIVE_LEVEL "Backlight Active Level"           // M7更改
#define SET_LABEL_BACKLIGHT_INACTIVE_LEVEL "Backlight Inactive Level"       // M7更改
#define SET_LABEL_BACKLIGHT_TIME "Backlight Time"
#define SET_LABEL_WALLPAPPER "Wallpaper"
#define SET_LABEL_KEY_AS_SEND "Key As Send"
#define SET_LABEL_HISTORY_RECORD "History Record"
#define SET_LABEL_NUMBER "Number"
#define SET_LABEL_HOTLINE_DELAY "Hotline Delay 0-10(s)"
#define SET_LABEL_PPPOE_USER "PPPoE User"
#define SET_LABEL_PPPOE_PWD "PPPoE PWD"
#define SET_LABEL_IPV6_IP_PREFIX "IPv6 IP Prefix"
#define SET_LABEL_COMMON "Common"
#define SET_LABEL_MAC_ORIENTED "MAC-Oriented"
#define SET_LABEL_ACCOUNT "Account"
#define SET_LABEL_NO "No."
#define SET_LABEL_KEYPRESS_SOUND "Keypress Sound"
#define SET_LABEL_IP_MODE "IPAddress Mode"
#define SET_LABEL_IPADDRESS_MODE "IPaddress Mode"
#define SET_LABEL_LAN_TYPE "LAN Type"
#define SET_LABEL_LAN_IP "LAN IP"
#define SET_LABEL_LAN_MASK "LAN Mask"
#define SET_LABEL_MODEL "Model"
#define SET_LABEL_HARDWARE "Hardware"
#define SET_LABEL_PRODUCT_ID "Product ID"
#define SET_LABEL_NEW "new"
#define SET_LABEL_OLD "old"
#define SET_LABEL_MAIL "mail"
#define SET_LABEL_CERTIFICATE "Certificate"
#define SET_LABEL_FACTORY_INSTALLED "Factory Installed"
#define SET_LABEL_NOT_INSTALLED "Not Installed"
#define SET_LABEL_RESET "Reset"
#define SET_LABEL_REBOOT "Reboot"
#define SET_LABEL_NO_EXP "No EXP"
#define SET_LABEL_CONTRAST_LEVEL "Contrast Level"


//页面提示
#define SET_NOTICE_NONE "None"
#define SET_NOTICE_EMPTY "Empty"

//提示语
#define SET_TIP_LOADING "Loading. Please wait..."
#define SET_TIP_LOAD_FAILED_NOTIFY "Load Failed!"
#define SET_TIP_LOAD_FAILED "Load Failed"
#define SET_TIP_SAVING "Saving. Please wait..."
#define SET_TIP_DELETING "Deleting. Please wait..."
#define SET_TIP_QUERYING "Querying. Please wait..."
#define SET_TIP_UNAUTHORIZED "Your account unauthorized."
#define SET_TIP_FAILED_RETRY "Failed. Please retry..."

#define SET_TIP_COPY_TO_ALL_LINES "Copy to All Lines?"
#define SET_TIP_SUCCESS_SAVED "Success Saved!"
#define SET_TIP_SAVE_FAILED "Save Failed!"
#define SET_TIP_SAVED_CONFIG_FAILED_RETRY "Save Config Failed, Please Retry!"
#define SET_TIP_OUTBOUND_ALTERNATE_NUMBER_INVALID "Outbound Alternate Number Invalid"
#define SET_TIP_DELETE_LOCATION "Delete location?"
#define SET_TIP_DELETE_ALL_LOCATIONS "Delete all locations?"

#define SET_TIP_NAME_INVALIDE "Number Invalid"
#define SET_TIP_NUMBER_EXISTS "Number exists"

#define SET_TIP_XSI_IS_EMPTY "XSI is empty"

#define SET_TIP_NO_BLUETOOTH_ADAPTER_FOND "No Bluetooth Adapter Found."
#define SET_TIP_NO_FOND_BLUETOOTH_ADAPTER "No found bluetooth adapter."
#define SET_TIP_CONNECT_FAILED "Connect failed."
#define SET_TIP_CONNECTING "Connecting.."
#define SET_TIP_DISCONNECT_FAILED "Disconnect Failed."
#define SET_TIP_DISCONNECTING "Disconnecting.."
#define SET_TIP_SAVED "Saved!"
#define SET_TIP_SCAN_FAILDED "Scan failed."
#define SET_TIP_CONNECT_SUCCESS "Connect Success."
#define SET_TIP_DISCONNECT_SUCCESS "Disconnect Success." //new
#define SET_TIP_REFRESH_fAILED "Refresh Failed."
#define SET_TIP_SCAN_fAILED "Scan Failed."
#define SET_TIP_SCAN_REFRESHING "Refreshing.."
#define SET_TIP_SCAN_SCANING "Scaning..."
#define SET_TIP_DELETE_SELETED_ITEM "Delete seleted item?"
#define SET_TIP_DELETE_ALL_ITEM "Delete all item?"
#define SET_TIP_DELETE_ALL_ITEMS "Delete All items?"
#define SET_TIP_LOGINING "Login..."
#define SET_TIP_LOGIN_FAILED "Login Failed."
#define SET_TIP_USER_ID_CANNOT_BE_EMPTY "UserID Can't be Empty!"
#define SET_TIP_LANGUAGE_INITIALIZING "Language initializing. Please wait..."
#define SET_TIP_SET_FAILED "Set failed!"
#define SET_TIP_VLAN_UNSUPPORTED_IN_PPPOE "VLAN unsupported in PPPoE!"
#define SET_TIP_LOAD_CONFIG_DATA_FAILED "Load Config Data Failed!"
#define SET_TIP_GET_CONFIGDATA_FAILED_RETRY "GetConfigData Failed, Please Retry!"
#define SET_TIP_REBOOT_THE_PHONE "Reboot the phone?"
#define SET_TIP_DETERMINED_RESTORE_FACTORY "Determined to restore the factory settings?"
#define SET_TIP_NOTE "Note"
#define SET_TIP_RESETING_PLEASE_WAIT "Reseting,Please wait..."
#define SET_TIP_OLD_PASSWORD_INCORRECT "The old password is incorrect!"
#define SET_TIP_CONFIRM_PWD_NOT_SAME_WITH_NEW_PWD "Confirm password must be the same with the new password!"
#define SET_TIP_FAIL_TO_MODIFY_PWD "Failed to modify password!"
#define SET_TIP_DELETE_FAILED "Delete Failed!"
#define SET_TIP_INVALID_NUMBER "Invalid Number"
#define SET_TIP_NUMBER_ALREADY_EXISTS "Number already exists!"
#define SET_TIP_DELE_NUMBERS "Delete numbers"
#define SET_TIP_NEED_A_NUMBER "Need a Number"
#define SET_TIP_MEMORY_FULL "Memory Full!"
#define SET_TIP_DELETE_ALL_NUMBERS "Delete all numbers"
#define SET_TIP_AUTOP_PROVISION_NOW "Auto provision now?"
#define SET_TIP_SYSTEM_WALLPAPPER_CANNOT_BE_DELETED "System Wallpaper Cannot be Deleted!!"
#define SET_TIP_DELETE_SELECTED_WALLPAPPER "Delete selected wallpapper?"
#define SET_TIP_DELETE_SUCCESSED "Delete successed"
#define SET_TIP_SET_FAILLY "Set failly!" //NEW
#define SET_TIP_PLEASE_INPUT_A_NONEMPTY_NAME "Please input a nonempty name" //NEW
#define SET_TIP_USER_MODE_CHANGED "User mode changed!" //New
// AskPassword
#define SET_TIP_PASSWORD_CANNOT_BE_SAPCE_ONLY "Password can't have space only" //NEW
#define SET_TIP_PASSWORD_CANNOT_BE_EMPTY "Password can't be empty"
#define SET_TIP_REGISTER_NAME_IS_INVALID "Register name is invalid!"
#define SET_TIP_USER_NAME_IS_INVALID "User name is invalid!"
#define SET_TIP_PASSWORD_IS_INVALID "Password is invalid!"
#define SET_TIP_SIP_SERVER1_IS_INVALID "SIP server1 is invalid!"
#define SET_TIP_SIP_SERVER2_IS_INVALID "SIP server2 is invalid!"
#define SET_TIP_PASSWORD_DONNOT_HAVE_SPACE_ONLY "Password can't have space only"
#define SET_TIP_PASSWORD_CANNOT_BE_EMPTY "Password can't be empty"

// HotDeskBase
#define SET_TIP_HAS_CONNECTED "Has Connected"

#define SET_TIP_LABEL_IS_INVALID "Label is invalid!"
#define SET_TIP_DISPLAY_NAME_IS_INVALID "Display name is invalid!"
#define SET_TIP_OUTBOUND_PROXY_IS_INVALID "Outbound proxy is invalid!"
#define SET_TIP_STUN_SERVER_IS_INVALID "STUN server is invalid!"
#define SET_TIP_FORWARD_TO_IS_INVALID "Forward to is invalid!"
#define SET_TIP_OFF_CODE_IS_INVALIDE "Off code is invalid!"
#define SET_TIP_OFF_CODE_CANNOT_BE_EMPTY "Off code can't be empty!"
#define SET_TIP_ON_CODE_IS_INVALIDE "On code is invalid!"
#define SET_TIP_REDIAL_INTERVAL_IS_INVALID "Redial Interval is invalid!"
#define SET_TIP_REDIAL_INTERVAL_SHOULD_BE_1_TO_300 "Redial Interval should be 1-300!"
#define SET_TIP_REDIAL_TIME_IS_INVALID "Redial Time is invalid!"
#define SET_TIP_REDIAL_TIME_SHOULD_BE_1_TO_300 "Redial Time should be 1-300!"
#define SET_TIP_OFF_CODE_CANNOT_EMPTY_WHEN_ON_CODE_IS_SET  "Off Code could not be empty when On Code is set!"
#define SET_TIP_NTP_SERER_1_IS_INVALID "NTP server1 is invalid!"
#define SET_TIP_NTP_SERER_2_IS_INVALID "NTP server2 is invalid!"
#define SET_TIP_VALUE_IS_INVALID "Value is invalid!"
#define SET_TIP_EXTENSION_IS_INVALID "Extension is invalid!"
#define SET_TIP_AUTOBLFLIST_IS_ON_MANUALLY_CONFIGING_IS_FORBIDEN "AutoBLFList is on, manually configing is forbiden!"
#define SET_TIP_AUTOFAVORITE_IS_ON_MANUALLY_CONFIGING_IS_FORBIDEN "AutoFavorite is on, manually configing is forbiden!"
#define SET_TIP_URL_IS_INVALID "URL is invalid!"
#define SET_TIP_BRIDGEID_IS_INVALID "BridgeID is invalid!"
#define SET_TIP_INVALID_DTMF_VALUE "Invalid DTMF value!"
#define SET_TIP_INVALID_PAGING_VALUE "Invalid Paging Value!"
#define SET_TIP_INVALID_DHCP_START_IP_ADDRESS "Invalid DHCP Start IP Address!"
#define SET_TIP_INVALID_DHCP_END_IP_ADDRESS "Invalid DHCP End IP Address!"
#define SET_TIP_INVALID_IP_ADDRESS "Invalid IP Address!"
#define SET_TIP_INVALID_SUB_NET_MASK "Invalid Subnet Mask!"
#define SET_TIP_HTTP_PORT_SHOLD_BE_1_65535 "Http port should be 1-65535!"
#define SET_TIP_HTTPS_PORT_SHOLD_BE_1_65535 "Https port should be 1-65535!"
#define SET_TIP_NEW_PASSWORD_IS_INVALID "New password is invalid!"
#define SET_TIP_PINS_DO_NOT_MATH "PINs don't match!"
#define SET_TIP_CALL_OFF_CODE_IS_INVALID "Call off code is invalid!"
#define SET_TIP_CALL_OFF_CODE_CANNOT_BE_EMPTY "Call off code can't be empty!"
#define SET_TIP_CALL_ON_CODE_IS_INVALID "Call on code is invalid!"
#define SET_TIP_REJECT_OFF_CODE_IS_INVALID "Reject off code is invalid!"
#define SET_TIP_REJECT_OFF_CODE_CANNOT_BE_EMPTY "Reject off code can't be empty!"
#define SET_TIP_REJECT_ON_CODE_IS_INVALID "Reject on code is invalid!"
#define SET_TIP_NUMBER_IS_INVALID "Number is invalid!"
#define SET_TIP_HOTLINE_DELAY_IS_INVALID "Hotline delay is invalid!"
#define SET_TIP_HOTLINE_DELAY_SHOULD_BE_0_10 "Hotline delay should be 0-10!"
#define SET_TIP_PPPOE_PASSWROD_IS_INVALID "PPPoE Password is invalid!"
#define SET_TIP_PPPOE_USER_IS_INVALID "PPPoEUser is invalid!"
#define SET_TIP_IPv4_SUBNET_MASK_IS_INVALID "IPv4 Subnet mask is invalid!"
#define SET_TIP_COMM_IS_INVALID "Common is invalid!"
#define SET_TIP_MAC_ORIENTED_IS_INVALID "MAC oriented is invalid!"
#define SET_TIP_VOICE_NUMBER_IS_INVALID "Voice Number is invalid!"
#define SET_TIP_ACCOUNT_NOT_USABLE "Account Not Usable!"


//页面标题
#define SET_TITLE_DISPOSITION_CODE "Disposition Code"
#define SET_TITLE_EMERGENCY_ESCALATION "Emergency Escalation"
#define SET_TITLE_ACD_INITIAL_STATE "Initial State"
#define SET_TITLE_LABLE_ACD_STATE "ACD State" //MULTI
#define SET_TITLE_ACD_UNAVAILABLE_REASON "Unavailable Reason Code"
#define SET_TITLE_LOCATION_EDIT "Edit Location"
#define SET_TITLE_LOCATIONS "Locations"
#define SET_TITLE_LOATION_NEW "New Location"
#define SET_TITLE_LINE_SELECT "Line Select"
#define SET_TITLE_FORWARD_OPTION "Forward Option"
#define SET_TITLE_CUSTOM_DND "Custom DND"
#define SET_TITLE_ACD_LOGIN "ACD Login"
#define SET_TITLE_GUEST_LOGIN "Guest Login"
#define SET_TITLE_LABEL_IPV4_STATUS "IPV4 Status" //MULTI
#define SET_TITLE_LABEL_IPV6_STATUS "IPV6 Status"
#define SET_TITLE_OPTION_ROUTER "Router" //MULTI
#define SET_TITLE_ADD_NUMBER "Add Number"
#define SET_TITLE_EDIT_NUMBER "Edit Number"
#define SET_TITLE_PHONE_NUMBERS "Phone Numbers"
#define SET_TITLE_IPV4_WAN_PORT "IPV4 WAN Port"
#define SET_TITLE_IPV6_WAN_PORT "IPV6 WAN Port"

//softkey
#define SET_OPERATE_OPTION_EXIT "Exit"
#define SET_OPERATE_OPTION_EXIT_DISPOSITION_CODE "Exit_Disposition_Code"
#define SET_OPERATE_ALL_LINES "All Lines"
#define SET_OPERATE_REMOVE "Remove"
#define SET_OPERATE_ADD "Add"
#define SET_OPERATE_DELETE_ALL "Delete All"
#define SET_OPERATE_SAVE "Save"
#define SET_OPERATE_DISCONNECT "Disconnect"
#define SET_OPERATE_BACK "Back"
#define SET_OPERATE_REFRESH "Refresh"
#define SET_OPERATE_SCAN "Scan"
#define SET_OPERATE_ALL_ON "All On"
#define SET_OPERATE_ALL_OFF "All Off"
#define SET_OPERATE_LOGIN "Login"

#define SET_OPERATE_ACCOUNT_ID                  "Account ID"
#define SET_OPERATE_VALUE                       "Value"
#define SET_OPERATE_LABEL                       "Label"
#define SET_OPERATE_SERVER                      "Server"
#define SET_OPERATE_USER_NAME                   "User Name"
#define SET_OPERATE_TYPE                        "Type"
#define SET_OPERATE_KEY_EVENT                   "Key Event"
#define SET_OPERATE_KEY_TYPE                    "Key Type"
#define SET_OPERATE_EXTENSION                   "Extension"
#define SET_OPERATE_URL                         "URL"
#define SET_OPERATE_URL_RECORD                  "URL Record"
#define SET_OPERATE_BRIDGEID                    "BridgeID"
#define SET_OPERATE_PIN_ID                      "PIN/ID"
#define SET_OPERATE_XML_GROUP                   "XML Group"
#define SET_OPERATE_LOCAL_GROUP                 "Local Group"
#define SET_OPERATE_BROADSOFT_GROUP             "BroadSoft Group"

/********************************************************************
*****************************NETWORK*******************************
********************************************************************/
#define NETWORK_VID_NUMBER_IS_INVALID "VID nubmer is invalid!"
#define NETWORK_TIP_PRIORITY_IS_INVALID "Priority is invalid!"
#define NETWORK_VID_NUMBER_IS_INVALID "VID nubmer is invalid!"
#define NETWORK_TIP_PRIORITY_IS_INVALID "Priority is invalid!"
#define NETWORK_TIP_VID_NUMBER_SHOULD_BE_1_4094 "VID number should be 1-4094!"
#define NETWORK_TIP_PRIORITY_SHOULD_BE_0_7 "Priority should be 0-7!"
#define NETWORK_TIP_PLEASE_UPLOAD_VPN_CONFIG_FILE_FIRSTLY "Please upload VPN config file firstly!"
#define NETWORK_TIP_IDENTITY_IS_INVALID "Identity is invalid!"
#define NETWORK_TIP_IP_ADDRESS_IS_INVALID "IP address is invalid!"
#define NETWORK_TIP_GATEWAY_IS_INVALID "Gateway is invalid!"
#define NETWORK_TIP_PRI_DNS_IS_INVALID "Pri.DNS is invalid!"
#define NETWORK_TIP_SEC_DNS_IS_INVALID "Sec.DNS is invalid!"

/********************************************************************
*****************************Directory*******************************
********************************************************************/
#define DIRECTORY_NAME_DEFAULT                  "Default"
#define DIRECTORY_NAME_FRIEND                   "Friend"
#define DIRECTORY_NAME_FAMILY                   "Family"
#define DIRECTORY_NAME_CUSTOMER                 "Customer"

/********************************************************************
*****************************Dsskey*******************************
********************************************************************/
#define  DSSKEY_LABEL_BLF_LIST                  "BLF List"
#define  DSSKEY_LABEL_VOIC_EMAIL            "Voice Mail"
#define  DSSKEY_LABEL_PICKUP                    "Pick Up"
#define  DSSKEY_LABEL_GPICKUP                   "Group Pick Up"
#define  DSSKEY_LABEL_CALL_PARK                 "Call Park"
#define  DSSKEY_LABEL_INTERCOM                  "Intercom"
#define  DSSKEY_LABEL_DTMF                      "DTMF"
#define  DSSKEY_LABEL_PREFIX                    "Prefix"
#define  DSSKEY_LABEL_LOCA_LGROUP           "Local Group"
#define  DSSKEY_LABEL_XML_GROUP                 "XML Group"
#define  DSSKEY_LABEL_XML_BROWSER           "XML Browser"
#define  DSSKEY_LABEL_LDAP                      "LDAP"
#define  DSSKEY_LABEL_BRAODSOFT_GROUP       "BroadSoft Group"
#define  DSSKEY_LABEL_CONFERENCE            "Conference"
#define  DSSKEY_LABEL_FORWARD                   "Forward"
#define  DSSKEY_LABEL_TRANSFER                  "Transfer"
#define  DSSKEY_LABEL_HOLD                      "Hold"
#define  DSSKEY_LABEL_DND                           "DND"
#define  DSSKEY_LABEL_CALL_RETURN           "Call Return"
#define  DSSKEY_LABEL_SMS                           "SMS"
#define  DSSKEY_LABEL_RECORD                    "Record"
#define  DSSKEY_LABEL_URL_RECORD            "URL Record"
#define  DSSKEY_LABEL_PAGING                    "Paging"
#define  DSSKEY_LABEL_GROUP_LISTEN          "Group Listening"
#define  DSSKEY_LABEL_PUBLIC_HOLD           "Public Hold"
#define  DSSKEY_LABEL_PRIVATE_HOLD          "Private Hold"
#define  DSSKEY_LABEL_ZERO                      "Zero Touch"
#define  DSSKEY_LABEL_URL                           "URL"
#define  DSSKEY_LABEL_HOTDESKING            "Hot Desking"
#define  DSSKEY_LABEL_FAVORITES                 "Directories"
#define  DSSKEY_LABEL_KEYPAD_LOCK           "KeyGuard"
#define  DSSKEY_LABEL_MEET_ME_CONFERENCE  "Meet-me"
#define  DSSKEY_LABEL_ACD                           "ACD"
#define  DSSKEY_LABEL_HOTELING                  "Hoteling"
#define  DSSKEY_LABEL_ACD_TRACE             "Trace"
#define  DSSKEY_LABEL_DISPCODE                  "DispCode"
#define  DSSKEY_LABEL_EMERGENCY                 "Emergency"
#define  DSSKEY_LABEL_RETRIEVE_PARK         "RetrievePark"
#define  DSSKEY_LABEL_BUDDIES                   "Buddies"
#define  DSSKEY_LABEL_NETWORK_FAVORITE  "NetworkFavorites"
#define  DSSKEY_LABEL_MY_STATUS                 "My Status"

#define  DSSKEY_LABEL_KEY                           "Key"
#define  DSSKEY_LABEL_SHARE_LINE            "Share Line"
#define  DSSKEY_LABEL_EXTENSION                 "Extension"
#define  DSSKEY_LABEL_SEIZING                   "Seizing"
#define  DSSKEY_LABEL_CALLING                   "Calling"
#define  DSSKEY_LABEL_RINGING                   "Ringing"
#define  DSSKEY_LABEL_TALKING                   "Talking"
#define  DSSKEY_LABEL_PARK                      "Park"
#define  DSSKEY_LABEL_BLF                           "BLF"
#define  DSSKEY_LABEL_CALL_OUT                  "Callout"
#define  DSSKEY_LABEL_HOLD                      "Hold"
#define  DSSKEY_LABEL_FAVORITE                  "Favorite"
#define  DSSKEY_LABEL_UC_FAVORITE               "UC Favorite"

/********************************************************************
*****************************Zero SPTouch****************************
********************************************************************/

//CDlgZeroNetwork_VLAN
#define ZERO_LABEL_WAN_PORT_VLAN "WAN Port VLAN"
#define ZERO_LABEL_VID_NUMBER "VID Number"
#define ZERO_LABEL_PRIORITY "Priority"
#define ZERO_TIP_VLAN_UNSUPPORTED_IN_PPPOE "VLAN unsupported in PPPoE!"
#define ZERO_TITLE_NOTE "Note"

//CDlgZeroNetwork_VPN
#define ZERO_LABEL_VPN_ACTIVE "VPN Active"

//CDlgZeroNetworkX_Mode
#define ZERO_COMBOBOX_DISABLED "Disabled"
#define ZERO_COMBOBOX_EAP_MD5 "EAP-MD5"
#define ZERO_COMBOBOX_EAP_TLS "EAP-TLS"
#define ZERO_COMBOBOX_PEAP_MSCHAPV2 "PEAP-MSCHAPV2"
#define ZERO_COMBOBOX_EAP_TTLS_EAP_MSCHAPV2 "EAP-TTLS/EAP-MSCHAPv2"
#define ZERO_LABEL_802_1X_MODE "802.1x Mode"
#define ZERO_LABEL_IDENTITY "Identity"

//CDlgZeroSPTouch
#define ZERO_LABEL_USER_NAME "User Name"
#define ZERO_TITLE_REDIRECTOR "Redirector"
#define ZERO_TITLE_NETWORK "Network"
#define ZERO_TITLE_STATUS "Status"
#define ZERO_TITLE_AUTO_PROVISION "Auto Provision"
#define ZERO_TITLE_UPDATE           "Update"
#define ZERO_TITLE_ZERO_SP_TOUCH "Zero SP Touch"
#define ZERO_OPERATE_STATUS "Status"
#define ZERO_OPERATE_NEXT "Next"
#define ZERO_OPERATE_SUBMIT "Submit"
#define ZERO_OPERATE_EXIT "Exit"
#define ZERO_LABEL_UPDATE_OK_OR_CANCEL "Update, ok or cancel?"
#define ZERO_LABEL_CONFIG_UPDATING "Config Updating"
#define ZERO_LABEL_UPDATE_FINISH "Update finish"
#define ZERO_LABEL_NETWORK_CHANGED_REBOOTING "Network changed. Rebooting"
#define ZERO_LABEL_UPDATE_SKIPPED "Update Skipped"
#define ZERO_LABEL_NETWORK_CHECKING "Network Checking..."
#define ZERO_LABEL_NETWORK_UNAVAILABLE "Network Unavailable"
#define ZERO_LABEL_SENDING_PROVISION_REQUESTS "Sending Provision Requests..."
#define ZERO_LABEL_REDIRCT_UPDATING_FAILED "Redirct Updating Failed"
#define ZERO_TIP_S " s"

//DlgZeroAutoProvision
#define ZERO_TIP_AUTO_PROVISION_NOW "Auto provision now?"
#define ZERO_LABEL_URL "URL"
#define ZERO_LABEL_USER_NAME "User Name"

//CDlgZeroNetwork

//CDlgZeroNetworkIPMode
#define ZERO_COMBOBOX_IPV4 "IPv4"
#define ZERO_COMBOBOX_IPV6 "IPv6"
#define ZERO_COMBOBOX_IPV4_IPV6 "IPv4 & IPv6"
#define ZERO_LABEL_IP_MODE "IP Mode"

//CDlgZeroNetworkWANPort
#define ZERO_TITLE_IPV4_WAN_PORT "IPV4 WAN Port"
#define ZERO_TITLE_IPV6_WAN_PORT "IPV6 WAN Port"
#define ZERO_COMBOBOX_DHCP "DHCP"
#define ZERO_COMBOBOX_PPPOE "PPPoE"
#define ZERO_COMBOBOX_STATIC_IP "Static IP"

#define ZERO_TIP_HAS_BEEN_USED "has been used!"
#define ZERO_TITLE_WARNING "Warning"
#define ZERO_LABEL_IPV4_WAN_TYPE "IPv4 WAN Type"
#define ZERO_LABEL_PPPOE_USER "PPPoE User"
#define ZERO_LABEL_PPPOE_PWD "PPPoE PWD"
#define ZERO_LABEL_IPV4_IP "IPv4 IP"
#define ZERO_LABEL_IPV4_SUBNET_MASK "IPv4 Subnet Mask"
#define ZERO_LABEL_IPV4_GATEWAY "IPv4 Gateway"
#define ZERO_LABEL_IPV4_PRI_DNS "IPv4 Pri.DNS"
#define ZERO_LABEL_IPV4_SEC_DNS "IPv4 Sec.DNS"
#define ZERO_LABEL_IPV6_WAN_TYPE "IPv6 WAN Type"
#define ZERO_LABEL_IPV6_IP "IPv6 IP"
#define ZERO_LABEL_IPV6_PRI_DNS "IPv6 Pri.DNS"
#define ZERO_LABEL_IPV6_SEC_DNS "IPv6 Sec.DNS"
#define ZERO_LABEL_IPV6_IP_PREFIX "IPv6 IP Prefix"
#define ZERO_LABEL_IPV6_PREFIX "IPv6 Prifix"
#define ZERO_LABEL_IPV6_DEFAULT_GATEWAY "IPv6 Default Gateway"
#define ZERO_LABEL_IPv4_DEFAULT_GATEWAY "IPv4 Default Gateway"
#define ZERO_LABEL_SERVER_URL "Server URL"

#define ZERO_TIP_BRIDGE_MODE_UNSUPPORTED_IN_PPPOE "Bridge mode unsupported in PPPoE!"
#define ZERO_TIP_USER_NAME_IS_INVALID "User name is invalid!"
#define ZERO_TIP_PASSWORD_IS_INVALID "Password is invalid!"
#define ZERO_TIP_IP_ADDRESS_HAS_BEEN_USED "IP address has been used!"
#define ZERO_TIP_SUBNET_MASK_IS_INVALID "Subnet mask is invalid!"
#define ZERO_TIP_IPV6_SUBNET_MASK_IS_INVALID "IPv6 Subnet mask is invalid!"


/********************************************************************
*****************************Zero SPTouch****************************
********************************************************************/
//DlgZeroAutoProvision
#define ZERO_TIP_URL_IS_INVALID "URL is invalid!"
#define ZERO_TIP_SERVER_URL_CANNOT_BE_EMPTY "Server URL can't be empty!"



/********************************************************************
***************************** BaseUI ****************************
********************************************************************/
// FrameSearchTitle
#define BASEUI_TIP_SEARCH_RESULT "Search Result"

// CDlgSubMenu
#define BASEUI_OPERATE_NEXT "Next"
#define BASEUI_TIP_NETWORK_CONFIGURATION_HAS_CHANGED_SHALL_BECOME_EFFECTIVE_AFTER_THE_RESTART "Network configuration has changed, shall become effective after the restart?"
#define BASEUI_TIP_DO_YOU_WANT_TO_DISCARD_YOUR_CHANGE "Do you want to discard your change?"
#define BASEUI_TITLE_MAIN_MENU "Main Menu"

/*********************************************************************
*****************************MAINWND**********************************
**********************************************************************/
#define MAINWND_LABEL_AUTO_CONNECT "Auto Connect:"

#define MAINWND_OPEATE_MOVE_UP "Move Up"
#define MAINWND_OPEATE_MOVE_DOWN "Move Down"
#define MAINWND_OPERATE_VIEW "View"
#define MAINWND_OPERATE_BLOCK "Block"

#define MAINWND_TIP_RETRIEVE_FAILED "Retrieve Failed"
#define MAINWND_TIP_FIRMWARE_UPDATE "Firmware Update..."
#define MAINWND_TIP_ALLOW_REMOTE_CONTROL "Allow Remote Control?"

#define MAINWND_NOTE_UNLOCK_PIN "Unlock PIN"
#define MAINWND_NOTE_NO_SERVICE "No Service"
#define MAINWND_NOTE_USER_ID "User ID"


/********************************************************************/
#define UC_OPTION_CHATTY "CHATTY"
#define UC_OPTION_ONLINE "Online"
#define UC_OPTION_AWAY "Away"
#define UC_OPTION_EXTENDED_AWAY "Extended Away"
#define UC_OPTION_BUSY "Busy"
#define UC_OPTION_OFFLINE "Offline"
#define UC_OPTION_UNKNOW "Unknow"


/************************************************************************/
#define MSGUI_LABEL_EMPTY "(Empty)"
#define MSGUI_LABEL_FROM "From"
#define MSGUI_LABEL_TO "To"
#define MSGUI_LABEL_TTO "To:"

#define MSGUI_TITILE_NEW_MESSAGE "New Message"

#define MSGUI_TIP_CLEAR_THIS_GROUP_MESSAGE "Clear this group messages?"
#define MSGUI_TIP_DELETE_THE_SELECT_MESSAGE "Delete the selected message?"
#define MSGUI_TIP_DELETE_THIS_MESSAGE "Delete this message?"
#define MSGUI_TIP_TARGET_CANNOT_BE_EMPTY "Target cannot be empty!"


#define DATETIME_TODY "Today"
#define DATETIME_YESTERDAY "Yesterday"

////////////////////
// StatusManager
#define LOGIC_KSZHINT_IP_CONFLICTD              "IP Conflicted"
#define LOGIC_KSZHINT_IP_CONFLICT               "IP conflict"
#define LOGIC_KSZHINT_NETWORK_UNAVAILABLE       "Network Unavailable"
#define LOGIC_KSZHINT_CABLE_DISCONNECT          "Cable Disconnect"
#define LOGIC_KSZHINT_CALL_CONTROL              "Call Control"
#define LOGIC_KSZHINT_MY_STATUS                 "My Status"
#define LOGIC_KSZHINT_BST_CALL_LOG              "BST Call Log"
#define LOGIC_IDLE_DIRECTORY_IDLE               "Directory_Idle"
#define LOGIC_IDLE_HISTORY_IDLE                 "History_Idle"
#define LOGIC_IDLE_DND                          "DND"
#define LOGIC_IDLE_MENU                         "Menu"
#define LOGIC_IDLE_SWITCHACCOUNT_IDLE           "SwitchAccount_Idle"
#define LOGIC_IDLE_SWITCHACCOUNTUP_IDLE         "SwitchAccountUp_Idle"
#define LOGIC_IDLE_SWITCHACCOUNTDOWN_IDLE       "SwitchAccountDown_Idle"
#define LOGIC_IDLE_SMS                          "SMS"
#define LOGIC_IDLE_NEWSMS_IDLE                  "NewSMS_Idle"
#define LOGIC_IDLE_STATUS                       "Status"
#define LOGIC_IDLE_REDIAL                       "Redial"
#define LOGIC_IDLE_CALLRETURN_IDLE              "CallReturn_Idle"
#define LOGIC_IDLE_FWD                          "FWD"
#define LOGIC_IDLE_PICKUP_IDLE                  "Pickup_Idle"
#define LOGIC_IDLE_GPICKUP                      "GPickup"
#define LOGIC_IDLE_SPEEDDIAL_IDLE               "SpeedDial_Idle"
#define LOGIC_IDLE_XML_IDLE                     "XML_Idle"
#define LOGIC_IDLE_LOCALMENU_IDLE               "LocalMenu_Idle"
#define LOGIC_IDLE_BROADSOFTMENU_IDLE           "BroadsoftMenu_Idle"
#define LOGIC_IDLE_LOCAL_IDLE                   "Local_Idle"
#define LOGIC_IDLE_BROADSOFT_IDLE               "Broadsoft_Idle"
#define LOGIC_IDLE_XMLMENU_IDLE                 "XMLMenu_Idle"
#define LOGIC_IDLE_XML_BROWSER                  "Xml Browser"
#define LOGIC_IDLE_PREFIX_IDLE                  "Prefix_Idle"
#define LOGIC_IDLE_KEYPADLOCK_IDLE              "KeypadLock_Idle"
#define LOGIC_IDLE_RETRIEVEPARK                 "RetrievePark"
#define LOGIC_IDLE_LDAP                         "LDAP"
#define LOGIC_IDLE_MEET_ME                      "Meet-me"
#define LOGIC_IDLE_DIRECTORIES                  "Directories"
#define LOGIC_IDLE_NETWORK_CALLLOG_IDLE         "NetworkCallLog_Idle"
#define LOGIC_IDLE_NETWORK_CALLLOG_GROUP_IDLE   "NetworkCalllogGroup_Idle"
#define LOGIC_IDLE_MY_STATUS                    "My Status"
#define LOGIC_IDLE_BUDDIES                      "Buddies"
#define LOGIC_IDLE_NETWORK_FAVORITE             "Network Favorite"
#define LOGIC_IDLE_HOT_DESKING                  "Hot Desking"

#endif  //T48_TRANSLATE_ID_DIFINE_H_
