#ifndef __SETTING_DATA_DEFINE_H__
#define __SETTING_DATA_DEFINE_H__

#include "innermsgdefine.h"

enum SettingMessage
{
    SETTING_MESSAGE_BEGIN = INNER_MSG_SETTING_MESSAGE_BEGIN,

    SETTING_MESSAGE_WIZARD_EXIT, // 设置向导退出

    SETTING_MESSAGE_AUTOPCONTROL_EXIT, // RPS/Zero退出

    SETTING_MESSAGE_END = INNER_MSG_SETTING_MESSAGE_END,
};


#endif //__SETTING_DATA_DEFINE_H__
