#ifndef __CALLCOMPLETION_MSG_DEFINE_H__
#define __CALLCOMPLETION_MSG_DEFINE_H__

#include "innermsgdefine.h"

// 账号模块消息定义
enum CALLCOMPLETION_MSG_DEFINE
{
    CALLCOMPLETION_MSG_FIRST = INNER_MSG_CALLCOMPLETION_FIRST,

    CALLCOMPLETION_MSG_ACTIVE,  //由callcompletion发出,是否弹出cc框

    CALLCOMPLETION_MSG_LAST = INNER_MSG_CALLCOMPLETION_LAST,
};

#endif // __CALLCOMPLETION_MSG_DEFINE_H__
