#ifndef DIRECTORY_DIRECTORYMESSAGEDEFINE_H_
#define DIRECTORY_DIRECTORYMESSAGEDEFINE_H_

#include "innermsgdefine.h"

// 联系人内部最大值为150

// 联系人消息定义.
enum DirectoryMessage
{
    DIRECTORY_MESSAGE_BEGIN = INNER_MSG_DIRECTORY_MESSAGE_BEGIN,

    // 本地联系人消息定义开始.
    LOCAL_DIRECTORY_MESSAGE_BEGIN = DIRECTORY_MESSAGE_BEGIN + 1,
    // 本地联系人消息, 重新加载本地组和联系人.
    LOCAL_DIRECTORY_RELOAD = LOCAL_DIRECTORY_MESSAGE_BEGIN + 1,
    // 拨出快捷菜单重新加载.
    DIRECTORY_SHORTCUT_RELOAD = LOCAL_DIRECTORY_MESSAGE_BEGIN + 2,
    // 本地联系人开始同步配置文件, 触发者是网页. LPARAM: 1-开始. 2-结束.
    LOCAL_DIRECTORY_RELOAD_CONFIG = LOCAL_DIRECTORY_MESSAGE_BEGIN + 3,
    //本地组名有改变消息, by yuyt
    LOCAL_GROUP_UPDATE,
    //本地联系人文件上传
    LOCAL_DIRECTORY_UPLOAD,
    //本地联系人文件下载
    LOCAL_DIRECTORY_DOWNLOAD,
    //Favorite联系人自动部署消息
    LOCAL_FAVORITE_CHANGED,
    // 本地联系人消息定义结束.
    LOCAL_DIRECTORY_MESSAGE_END = LOCAL_DIRECTORY_MESSAGE_BEGIN + 20,

    // 远程联系人消息定义开始.
    REMOTE_DIRECTORY_MESSAGE_BEGIN = LOCAL_DIRECTORY_MESSAGE_END + 1,
    // 远程联系人下载成功, LPARAM-0,成功; 1-失败. Extra-远程下载地址的URL.
    REMOTE_PHONEBOOK_DOWNLOADED_RESULT = REMOTE_DIRECTORY_MESSAGE_BEGIN + 1,
    // 远程联系人消息, 重新加载远程组和联系人.
    REMOTE_PHONEBOOK_RELOAD = REMOTE_DIRECTORY_MESSAGE_BEGIN + 2,
    // 远程联系人下载完成. wparm:groupId lparm:0/1 成功/失败
    REMOTE_PHONEBOOK_ALL_DOWNLOADED_FINISHED = REMOTE_DIRECTORY_MESSAGE_BEGIN + 3,
    // 开始更新远程联系人.
    REMOTE_PHONEBOOK_BEGIN_UPDATE = REMOTE_DIRECTORY_MESSAGE_BEGIN + 4,
    // 远程联系人消息定义结束.
    REMOTE_DIRECTORY_MESSAGE_END = REMOTE_DIRECTORY_MESSAGE_BEGIN + 20,

    // BroadSoft联系人消息定义开始.
    BROADSOFT_DIRECTORY_MESSAGE_BEGIN = REMOTE_DIRECTORY_MESSAGE_END + 1,
    // BroadSoft联系人下载成功, LPARAM-0,失败; 1-成功, 401-密码错误 如果成功:带上额外字段：bool（是否请求分页中），失败不额外带参数
    BROADSOFT_PHONEBOOK_DOWNLOADED_RESULT = BROADSOFT_DIRECTORY_MESSAGE_BEGIN + 1,
    // BroadSoft联系人消息, 重新加载BroadSoft组和联系人.
    BROADSOFT_PHONEBOOK_RELOAD = BROADSOFT_DIRECTORY_MESSAGE_BEGIN + 2,
    // BroadSoft Personal联系人Post成功, WPARAM: 联系人ID， LPARAM-0,成功; 1-失败
    BROADSOFT_PHONEBOOK_POST_RESULT = BROADSOFT_DIRECTORY_MESSAGE_BEGIN + 3,

    // BroadSoft联系人服务器搜索结果返回消息, LPARAM-0,失败; 1-成功, 401-密码错误，如果成功:带上额外字段：bool（是否请求分页中），失败不额外带参数
    BROADSOFT_PHONEBOOK_SERVERSEARCH_RESULT = BROADSOFT_DIRECTORY_MESSAGE_BEGIN + 4,
    // BroadSoft地址薄消息定义结束
    BROADSOFT_PHONEBOOK_MESSAGE_END = BROADSOFT_DIRECTORY_MESSAGE_BEGIN + 20,

    // BroadSoft BuddyList消息定义开始
    BROADSOFT_BUDDYLIST_MESSAGE_BEGIN = BROADSOFT_PHONEBOOK_MESSAGE_END + 1,
    // BroadSoft BuddyList刷新完成消息
    BROADSOFT_BUDDYLIST_REFRESH_FINISHED = BROADSOFT_BUDDYLIST_MESSAGE_BEGIN + 1,
    // BroadSoft BuddyList组有更改
    BROADSOFT_BUDDYLIST_GROUP_CHANGE = BROADSOFT_BUDDYLIST_MESSAGE_BEGIN + 2,
    // BroadSoft联系人消息定义开始.
    BROADSOFT_DIRECTORY_MESSAGE_END = BROADSOFT_BUDDYLIST_MESSAGE_BEGIN + 20,

    // LDAP消息定义开始.
    LDAP_MESSAGE_BEGIN = BROADSOFT_DIRECTORY_MESSAGE_END + 1,
    // LDAP状态改变, LPARAM-0(关闭) 1(开启).
    LDAP_STATUS_CHANGED = LDAP_MESSAGE_BEGIN + 1,


    //wparm: 0/1 失败/成功 401 鉴权错误  lparm : 0, ext:搜索关键字
    LDAP_SRARCH_RESULT = LDAP_STATUS_CHANGED + 1,

    // LDAP消息定义结束.
    LDAP_MESSAGE_END = LDAP_MESSAGE_BEGIN + 9,

    //本地搜索结果消息 wparm:0  Lparm:0/1 失败/成功  ext:SearchKey
    LOCAL_SEARCH_RESULT = LDAP_MESSAGE_END + 1,

    //本地搜索结果消息 wparm:0  Lparm:1 成功(失败不发消息)  ext:SearchKey
    SUPER_SEARCH_RESULT = LOCAL_SEARCH_RESULT + 1,

    PLCM_PHONEBOOK_ALL_DOWNLOADED_FINISHED = SUPER_SEARCH_RESULT + 1,

    BLUETOOTH_CONTACT_BEGIN = SUPER_SEARCH_RESULT + 10,

    //蓝牙联系人重新加载消息 wparm: 0 fail \ 1 suc
    BLUETOOTH_CONTACT_RELOAD,

    //蓝牙联系人下载结果 wparam 0 fail\ 1 suc\ 2 下载中断开
    BLUETOOTH_CONTACT_DOWNLOAD_RESULT,

    BLUETOOTH_CONTACT_END = BLUETOOTH_CONTACT_BEGIN + 10,

    // Metaswitch联系人消息定义开始.
    METASWITCH_DIRECTORY_MESSAGE_BEGIN = BLUETOOTH_CONTACT_END + 1,
    // Metaswitch联系人下载成功, LPARAM-0,失败; 1-成功, 401-密码错误
    METASWITCH_PHONEBOOK_DOWNLOADED_RESULT = METASWITCH_DIRECTORY_MESSAGE_BEGIN + 1,
    // Metaswitch联系人消息, 重新加载Metaswitch组和联系人.
    METASWITCH_PHONEBOOK_RELOAD = METASWITCH_DIRECTORY_MESSAGE_BEGIN + 2,
    // Metaswitch Personal联系人Post成功, WPARAM: 联系人ID， LPARAM-0,成功; 1-失败
    METASWITCH_PHONEBOOK_POST_RESULT = METASWITCH_DIRECTORY_MESSAGE_BEGIN + 3,

    // Metaswitch联系人服务器搜索结果返回消息, LPARAM-0,失败; 1-成功, 401-密码错误
    METASWITCH_PHONEBOOK_SERVERSEARCH_RESULT = METASWITCH_DIRECTORY_MESSAGE_BEGIN + 4,
    // Metaswitch地址薄消息定义结束
    METASWITCH_PHONEBOOK_MESSAGE_END = METASWITCH_DIRECTORY_MESSAGE_BEGIN + 50,

    // Cloud联系人消息定义开始.
    CLOUD_DIRECTORY_MESSAGE_BEGIN = BLUETOOTH_CONTACT_END + 1,
    // Cloud联系人下载成功, LPARAM-0,失败; 1-成功, 如果成功:带上额外字段：bool（是否请求分页中），失败不额外带参数
    CLOUD_PHONEBOOK_DOWNLOADED_RESULT = CLOUD_DIRECTORY_MESSAGE_BEGIN + 1,
    // Cloud联系人消息, 重新加载Cloud组和联系人.
    CLOUD_PHONEBOOK_RELOAD = CLOUD_DIRECTORY_MESSAGE_BEGIN + 2,
    // Cloud地址薄消息定义结束
    CLOUD_PHONEBOOK_MESSAGE_END = CLOUD_DIRECTORY_MESSAGE_BEGIN + 10,

    //wparm type lparm 0/1 失败/成功
    GENBAND_BOOK_REQ_RESULT = CLOUD_PHONEBOOK_MESSAGE_END + 1,

    GENBAND_BOOK_RELOAD = GENBAND_BOOK_REQ_RESULT + 1,

    DIRECTORY_MESSAGE_END = INNER_MSG_DIRECTORY_MESSAGE_END
};

// 联系人消息定义.
enum CallLogMessage
{
    CALLLOG_MESSAGE_BEGIN = INNER_MSG_CALLLOG_MESSAGE_BEGIN,

    // 本地历史记录消息定义开始.
    LOCAL_CALLLOG_MESSAGE_BEGIN = CALLLOG_MESSAGE_BEGIN + 1,

    // 未接来电通知消息, wParam: 0  lParam: 未接来电数量
    LOCAL_CALLLOG_MESSAGE_MISSED = LOCAL_CALLLOG_MESSAGE_BEGIN + 1,

    // 转接来电通知消息, wParam: 0  lParam: 转接来电数量
    LOCAL_CALLLOG_MESSAGE_FORWARD = LOCAL_CALLLOG_MESSAGE_BEGIN + 2,

    //本地历史记录上传
    LOCAL_CALLLOG_UPLOAD,

    // 本地历史记录消息定义结束.
    LOCAL_CALLLOG_MESSAGE_END = LOCAL_CALLLOG_MESSAGE_BEGIN + 10,

    // BroadSoft联系人消息定义开始.
    BROADSOFT_CALLLOG_MESSAGE_BEGIN = LOCAL_CALLLOG_MESSAGE_END + 1,
    // BroadSoftCallLog下载成功, LPARAM-1,成功; 0-失败, 401-密码错误 Extra-BroadSoft下载地址的URL.
    BROADSOFT_CALLLOG_DOWNLOADED_RESULT = BROADSOFT_CALLLOG_MESSAGE_BEGIN + 1,
    // 历史记录.
    BROADSOFT_CALLLOG_RELOAD = BROADSOFT_CALLLOG_MESSAGE_BEGIN + 2,
    // BroadSoft联系人消息定义开始.
    BROADSOFT_CALLLOG_MESSAGE_END = BROADSOFT_CALLLOG_MESSAGE_BEGIN + 50,

    // Metaswitch联系人消息定义开始.
    METASWITCH_CALLLOG_MESSAGE_BEGIN = BROADSOFT_CALLLOG_MESSAGE_END + 1,
    // Metaswitch下载成功, LPARAM-1,成功; 0-失败, 401-密码错误 Extra下载地址的URL.
    METASWITCH_CALLLOG_DOWNLOADED_RESULT = METASWITCH_CALLLOG_MESSAGE_BEGIN + 1,
    // Metaswitch重新加载
    METASWITCH_CALLLOG_RELOAD = METASWITCH_CALLLOG_MESSAGE_BEGIN + 2,
    // Metaswitch CallLog消息定义结束.
    METASWITCH_CALLLOG_MESSAGE_END = METASWITCH_CALLLOG_MESSAGE_BEGIN + 10,

    CALLLOG_MESSAGE_END = INNER_MSG_CALLLOG_MESSAGE_END
};

#endif  // DIRECTORY_DIRECTORYMESSAGEDEFINE_H_
