
#ifndef __TOOL_MSG_DEFINE_H__
#define __TOOL_MSG_DEFINE_H__

enum TOOL_MSG
{
    TOOL_MSG_BEGIN                      = DSK_MSG(DSK_MSG_TOOL, DSK_MSG_INDEX),

    TOOL_MSG_CPU_PROFILE_BEGIN          = TOOL_MSG_BEGIN + 1,
    TOOL_MSG_CPU_PROFILE_START          = TOOL_MSG_CPU_PROFILE_BEGIN + 1,
    TOOL_MSG_CPU_PROFILE_STOP           = TOOL_MSG_CPU_PROFILE_BEGIN + 2,
    TOOL_MSG_CPU_PROFILE_FLUSH          = TOOL_MSG_CPU_PROFILE_BEGIN + 3,
    TOOL_MSG_CPU_PROFILE_END            = TOOL_MSG_CPU_PROFILE_BEGIN + 10,

    TOOL_MSG_END,
};

#endif
