#ifndef __ANIMATION_DEFINE_H__
#define __ANIMATION_DEFINE_H__

// 动画类型
enum ANIMATION_TYPE
{
	ANIMATION_TYPE_BASE					= 0x00000000,				// 基础类
	ANIMATION_TYPE_VIEW					= 0x01000000,				// 视图动画基础类
	ANIMATION_TYPE_VIEW_ALPHA			= 0x01010000,				// 透明度动画类
	ANIMATION_TYPE_VIEW_MOVE			= 0x01020000,				// 视图移动动画类
	ANIMATION_TYPE_VIEW_SCALE			= 0x01030000,				// 视图缩放动画类(左顶点不变)
	ANIMATION_TYPE_GROUP				= 0x02000000,				// 动画组类
	ANIMATION_TYPE_PARALLEL_GROUP		= 0x02010000,				// 并行动画组类
	ANIMATION_TYPE_SEQUENTIAL_GROUP		= 0x02020000,				// 串行动画组类
	ANIMATION_TYPE_SCALE_TO				= 0x02010100,				// 缩放并移动动画类
};

// 动画插值类型
enum ANIMATION_INTERPOLATOR
{
	INTERPOLATOR_LINEAR,
	INTERPOLATOR_IN_QUAD,
	INTERPOLATOR_OUT_QUAD,
	INTERPOLATOR_IN_OUT_QUAD,
	INTERPOLATOR_OUT_IN_QUAD,
	INTERPOLATOR_IN_CUBIC,
	INTERPOLATOR_OUT_CUBIC,
	INTERPOLATOR_IN_OUT_CUBIC,
	INTERPOLATOR_OUT_IN_CUBIC,
	INTERPOLATOR_IN_QUART,
	INTERPOLATOR_OUT_QUART,
	INTERPOLATOR_IN_OUT_QUART,
	INTERPOLATOR_OUT_IN_QUART,
	INTERPOLATOR_IN_QUINT,
	INTERPOLATOR_OUT_QUINT,
	INTERPOLATOR_IN_OUT_QUINT,
	INTERPOLATOR_OUT_IN_QUINT,
	INTERPOLATOR_IN_SINE,
	INTERPOLATOR_OUT_SINE,
	INTERPOLATOR_IN_OUT_SINE,
	INTERPOLATOR_OUT_IN_SINE,
	INTERPOLATOR_IN_EXPO,
	INTERPOLATOR_OUT_EXPO,
	INTERPOLATOR_IN_OUT_EXPRO,
	INTERPOLATOR_OUT_IN_EXPO,
	INTERPOLATOR_IN_CIRC,
	INTERPOLATOR_OUT_CIRC,
	INTERPOLATOR_IN_OUT_CIRC,
	INTERPOLATOR_OUT_IN_CIRC,
	INTERPOLATOR_IN_ELASTIC,
	INTERPOLATOR_OUT_ELASTIC,
	INTERPOLATOR_IN_OUT_ELASTIC,
	INTERPOLATOR_OUT_IN_ELASTIC,
	INTERPOLATOR_IN_BACK,
	INTERPOLATOR_OUT_BACK,
	INTERPOLATOR_IN_OUT_BACK,
	INTERPOLATOR_OUT_IN_BACK,
	INTERPOLATOR_IN_BOUNCE,
	INTERPOLATOR_OUT_BOUNCE,
	INTERPOLATOR_IN_OUT_BOUNCE,
	INTERPOLATOR_OUT_IN_BOUNCE,
	INTERPOLATOR_IN_CURVE,
	INTERPOLATOR_OUT_CURVE,
	INTERPOLATOR_SINE_CURVE,
	INTERPOLATOR_COSINE_CURVE,
	INTERPOLATOR_CUSTOM,
};

#define ANIMATION_DEBUG 0

#endif
