#ifndef XB_POSITION_DEFINE
#define XB_POSITION_DEFINE

//预留给滚动条的宽度
const int   XML_SCROLL_WIDTH(49);
const int   XML_SCROLL_LEFT_SPACING(0);
const int   XML_SCROLL_RIGHT_SPACING(4);
const int   XML_TITLE_HEIGHT(43);

const int XML_SCROLL_BAR_TOP_SPACING = 0;
const int XML_SCROLL_BAR_BOTTOM_SPACING = 4;

#define INPUT_FRAME_LEFT_MARGIN 10
#define INPUT_FRAME_ROW_SPACING 7

#endif // XB_POSITION_DEFINE
