#ifndef ACCOUNT_MESSAGE_H_
#define ACCOUNT_MESSAGE_H_

#include "innermsgdefine.h"

enum AccountMessageDefine
{
    ACCOUNT_MESSAGE_BEGIN = INNER_MSG_ACCOUNT_MESSAGE_BEGIN,

    //Default Account Changed
    ACCOUNT_DEFAULT_CHANGED,  // WPARAM: 0, LPARAM: 0

    //Account Status Changed
    ACCOUNT_STATUS_CHANGED,  // WPARAM: Account Id, LPARAM: Old Account State

    //All Account Voice Mail Count Changed
    ACCOUNT_VOICE_MAIL_COUNT_CHANGED,  // WPARAM: bNewVoiceMail, LPARAM: 0/1 是否重新弹框;

    //VOICE MAIL 状态改变
    ACCOUNT_VOICE_MAIL_STATE_CHANGED, //WPARAM: AccountID,LPARAM 0/1 是否更新弹窗

    // PSTN账号相关消息
    ACCOUNT_PSTN_CREATED, // WPARAM: AccountID, LPARAM: 0
    ACCOUNT_PSTN_REMOVED, // WPARAM: AccountID, LPARAM: 0
    ACCOUNT_PSTN_STATUS_CHANGED, // WPARAM: AccountID, LPARAM: 0

    ACCOUNT_CLOUD_LOGIN_RESULT, //WPARAM: AccountID,LPARAM 0/- 0：成功 其他值：失败类型

    //账号配置变化
    ACCOUNT_CONFIG_CHANGE, //WPARAM: AccountID,LPARAM 0/- 0：

    ACCOUNT_MESSAGE_END = INNER_MSG_ACCOUNT_MESSAGE_END,
};

enum ACCOUNT_REGISTERED_SERVER
{
    ACCOUNT_REGISTERED_SERVER_UNKOWN = 0x10000,
    ACCOUNT_REGISTERED_SERVER_1 = 0x10001,
    ACCOUNT_REGISTERED_SERVER_2 = 0x10002,
    ACCOUNT_REGISTERED_SERVER_3 = 0x10003,
};

// GetBalance消息定义.
enum AccountGetBalanceMessage
{
    GET_BALANCE_MESSAGE_BEGIN = INNER_MSG_GET_BALANCE_BEGIN,
    GET_BALANCE_MESSAGE_LOADING,
    GET_BALANCE_MESSAGE_GET_RESULT,
    GET_BALANCE_MESSAGE_LOAD_ERROR,
    GET_BALANCE_MESSAGE_CLEAN_TIPS,
    GET_BALANCE_MESSAGE_END = INNER_MSG_GET_BALANCE_END
};
#endif  // ACCOUNT_MESSAGE_H_
