#ifndef __TESTMODE_MESSAGEDEFINE_H__
#define __TESTMODE_MESSAGEDEFINE_H__

#include "innermsgdefine.h"

enum TestModeMessage
{
    TESTMODE_MESSAGE_BEGIN = INNER_MSG_TESTMODE_MESSAGE_BEGIN,

    TESTMODE_MESSAGE_EXIT, // 测试模式退出

    TESTMODE_MESSAGE_END = INNER_MSG_TESTMODE_MESSAGE_BEGIN,
};

#endif // __TESTMODE_MESSAGEDEFINE_H__
