#ifndef __CC_MESSAGE_DEFINE_H__
#define __CC_MESSAGE_DEFINE_H__

enum ACDMessage
{
    ACD_MESSAGE_BEGIN = INNER_MSG_ACD_MESSAGE_BEGIN,

    //逻辑给外部模块发送ACD状态改变消息
    ACD_MESSAGE_STATUS_CHANGE = ACD_MESSAGE_BEGIN + 1,//wParam:Account ID   lParam: status  extra:char* Reason Code

    ACD_MESSAGE_QUEUE_STATUS, //wParam:Account ID

    ACD_MESSAGE_STATUS_UPDATE,  //wParam: line id           lParam: ACD_STATUS

    ACD_MESSAGE_ACTION_RESULT,  //wParam: line id           lParam: 0:SUCCSESS 1:FAIL

    ACD_MESSAGE_LOGIN_TIMEOUT,

    ACD_MESSAGE_LOGIN_FAIL,

#if IF_FEATURE_START2START_ACD
    ACD_MESSAGE_ACTION_AUTO_REFRESH,

    ACD_MESSAGE_S2S_STATUS_CHANGE,
#endif

    ACD_MESSAGE_END = INNER_MSG_ACD_MESSAGE_END,

};

enum HotelingMessage
{
    HOTELING_MESSAGE_BEGIN = INNER_MSG_HOTELING_MESSAGE_BEGIN,

    //逻辑给外部模块发送Hoteling状态改变消息
    HOTELING_MESSAGE_STATUS_CHANGE = HOTELING_MESSAGE_BEGIN + 1,//wParam:Account ID  lParam: status

    //逻辑层发给外部模块的Hoteling登陆请求超时消息
    HOTELING_MESSAGE_REQ_TIMEOUT = HOTELING_MESSAGE_BEGIN + 2,

    HOTELING_MESSAGE_REQ_FAIL = HOTELING_MESSAGE_BEGIN + 3,

    HOTELING_MESSAGE_END = INNER_MSG_HOTELING_MESSAGE_END,

};

enum MTSWACDMessage
{
    MTSW_ACD_MESSAGE_BEGIN = INNER_MSG_MTSW_ACD_MESSAGE_BEGIN,
    MTSW_ACD_GET_RESULT,
    MTSW_ACD_GET_FAILED,
    MTSW_ACD_MESSAGE_END = INNER_MSG_MTSW_ACD_MESSAGE_END,
};

#endif
