#ifndef DEFINE_IDLESCREENMODELMESSAGEDEFINE_H_
#define DEFINE_IDLESCREENMODELMESSAGEDEFINE_H_

#include "innermsgdefine.h"

enum IdleScreenModelMessageDefine
{
    IDLESCREENMODEL_MESSAGE_BEGIN = INNER_MSG_PHONESTATE_BEGIN,

    // VPN status changed, eg. on -> off, or off -> on. LPARAM 0-status off, 1-status on.
    IDLESCREENMODEL_VPN_STATUS_CHANGED = IDLESCREENMODEL_MESSAGE_BEGIN + 1,
    // Current Line changed. LPARAM-current line Id.
    IDLESCREENMODEL_CURRENT_LINE_ID_CHANGED = IDLESCREENMODEL_MESSAGE_BEGIN + 2,
    // BroadSoft contact used or not used. LPARAM 0-not used, 1-used.
    IDLESCREENMODEL_BROADSOFT_CONTACT_USED_CHANGED = IDLESCREENMODEL_MESSAGE_BEGIN + 3,
    // CallLog used or not used. LPARAM 0-not used, 1-used.
    IDELSCREENMODEL_CALLLOG_USED_CHANGED = IDLESCREENMODEL_MESSAGE_BEGIN + 4,
    // BroadSoft and CallLog switch changed. LPARAM 0-off, 1-on.
    IDLESCREENMODEL_BROADSOFT_AND_CALLLOG_SWITCH_CHANGED = IDLESCREENMODEL_MESSAGE_BEGIN + 5,
    // Hot desking status changed. LPARAM 0-off, 1-on.
    IDLESCREENMODEL_HOTDESKING_STATUS_CHANGED = IDLESCREENMODEL_MESSAGE_BEGIN + 6,
    // Current account Id changed. LPARAM current account Id.
    IDELSCREENMODEL_CURRENT_ACCOUNT_ID_CHANGED = IDLESCREENMODEL_MESSAGE_BEGIN + 7,

    IDLESCREENMODEL_MESSAGE_END = INNER_MSG_IDELSCREENMODEL_END,
};

#endif  // DEFINE_IDLESCREENMODELMESSAGEDEFINE_H_
