#ifndef PHONELIB_PHONESTATEMESSAGE_H_
#define PHONELIB_PHONESTATEMESSAGE_H_

#include "innermsgdefine.h"

enum PhoneStateMessageDefine
{
    PHONESTATE_MESSAGE_BEGIN = INNER_MSG_PHONESTATE_BEGIN,

    PHONESTATE_STATE_CHANGED = INNER_MSG_PHONESTATE_BEGIN + 1,  // WPARAM: PhoneState, LPARAM: 0-off, 1-on.

    // States changed, and posts some top of states..
    PHONESTATE_TOP_LIST_CHANGED = INNER_MSG_PHONESTATE_BEGIN + 2,

    PHONESTATE_REFRESH_STAUSBAR = INNER_MSG_PHONESTATE_BEGIN + 3, //PHONESTATE_TOP_LIST_CHANGED会引起idle弹窗

    PHONESTATE_SMS_CHANGED  = INNER_MSG_PHONESTATE_BEGIN + 4,
    PHONESTATE_SMS_POPUP_PROCESS    = INNER_MSG_PHONESTATE_BEGIN + 5,   //WPARAM:0/1,0:Destory,1:Check LPARAM:0/1, IsPlayRing
    PHONESTATE_SMS_FULLSCREEN_EXIT  = INNER_MSG_PHONESTATE_BEGIN + 6,   //WPARAM: 0/1,IsSingleSessionOnly

    PHONESTATE_ACD_STATUS_CHANGED = INNER_MSG_PHONESTATE_BEGIN + 7, //WPARAM:ACD Status

    PHONESTATE_TEST_USB = PHONESTATE_MESSAGE_BEGIN + 8, //PHONESTATE_TEST_USB触发测试模式USB切换UI绘图

    PHONESTATE_MESSAGE_END = INNER_MSG_PHONESTATE_END,
};

#endif  // PHONELIB_PHONESTATEMESSAGE_H_
