#ifndef _DEFINE_TIP_MESSAGEDEFINE_H_
#define _DEFINE_TIP_MESSAGEDEFINE_H_

#include "innermsgdefine.h"

// Video message definition.
enum CallCompletionMessageDefine
{
    CALLCOMPLETION_MESSAGE_BEGIN = INNER_MSG_CALLCOMPLETION_MESSAGE_BEGIN,

    // Call Completion可拨出, WPARAM-无, LPARAM-无.
    CALLCOMPLETION_ACTIVE = CALLCOMPLETION_MESSAGE_BEGIN + 1,


    CALLCOMPLETION_MESSAGE_END = INNER_MSG_CALLCOMPLETION_MESSAGE_END,
};

enum AutoProvisionMessageDefine
{
    AUTOPROVISION_MESSAGE_BEGIN = INNER_MSG_AUTOPROVISION_MESSAGE_BEGIN,
    // 显示是否要autop
    AUTOPROVISION_UPDATE_NOTICE = AUTOPROVISION_MESSAGE_BEGIN + 1,
    AUTOPROVISION_MESSAGE_END = INNER_MSG_AUTOPROVISION_MESSAGE_END,
};

#endif  // _DEFINE_TIP_MESSAGEDEFINE_H_
