#ifndef PHONELIB_FEATURESYNCMESSAGEDEFINE_H_
#define PHONELIB_FEATURESYNCMESSAGEDEFINE_H_

#include "message_define.h"

enum FeatureSyncMessageDefine
{
    FEATURESYNC_MESSAGE_BEGIN = INNER_MSG_FEATURESYNCMESSAGE_BEGIN,

    FEATURESYNC_SYNC_CHANGED = INNER_MSG_FEATURESYNCMESSAGE_BEGIN + 1,  // LPARAM: 0-sync is on, 1-sync is off.
    FEATURESYNC_SYNCALLACCOUNT_CHANGED = INNER_MSG_FEATURESYNCMESSAGE_BEGIN + 2,  // LPARAM: 0-no sync to all acount, 1-sync to all acount.

    FEATURESYNC_MESSAGE_END = INNER_MSG_FEATURESYNCMESSAGE_END,
};

#endif  // PHONELIB_FEATURESYNCMESSAGEDEFINE_H_
