#ifndef _DSSKEY_INNER_ENUM_TYPES_HEADER_
#define _DSSKEY_INNER_ENUM_TYPES_HEADER_


//翻页键提示优先级
enum DSS_KEY_PAGE_BUTTON_PRIORITY
{
    DSS_KEY_LED_PRIORITY_HIGHEST = 0,
    DSS_KEY_LED_PRIORITY_SECOND_HIGH,
    DSS_KEY_LED_PRIORITY_HIGH,
    DSS_KEY_LED_PRIORITY_NORMAL,
    DSS_KEY_LED_PRIORITY_LOW,
    DSS_KEY_LED_PRIORITY_SECOND_LOW,
    DSS_KEY_LED_PRIORITY_LOWEST
};

#endif

