#ifndef __INNER_MSG_DEFINE_H__
#define __INNER_MSG_DEFINE_H__

#include "service_dsk_interface.h"

// 各模块内部消息范围定义
enum INNER_MSG
{
    INNER_MSG_FIRST = DSK_MSG(DSK_MSG_LOGIC, DSK_MSG_INDEX),

    INNER_MSG_NONE,  // No message

    // 通话模块的内部消息
    INNER_MSG_TALK_FIRST,
    INNER_MSG_TALK_LAST = INNER_MSG_TALK_FIRST + 100,

    // CallCompletion内部消息
    INNER_MSG_CALLCOMPLETION_FIRST,
    INNER_MSG_CALLCOMPLETION_LAST = INNER_MSG_CALLCOMPLETION_FIRST + 10,

    // CommonUnits模块消息
    INNER_MSG_COMMON_UNITS_FIRST,
    INNER_MSG_COMMON_UNITS_LAST = INNER_MSG_COMMON_UNITS_FIRST + 20,

    // CallPark消息定义开始.
    INNER_MSG_CALL_PARK_MESSAGE_BEGIN,
    // CALLLOG消息定义结束.
    INNER_MSG_CALL_PARK_MESSAGE_END = INNER_MSG_CALL_PARK_MESSAGE_BEGIN + 20,

    // Idle消息定义开始.
    INNER_MSG_IDLE_MESSAGE_BEGIN,
    // Idle消息定义结束.
    INNER_MSG_IDLE_MESSAGE_END = INNER_MSG_IDLE_MESSAGE_BEGIN + 10,

    // DND message definition begin.
    INNER_MSG_DND_BEGIN,
    // DND message definition end.
    INNER_MSG_DND_END = INNER_MSG_DND_BEGIN + 20,

    // Forward message definition begin.
    INNER_MSG_FORWARD_BEGIN,
    // Forward message definition end.
    INNER_MSG_FORWARD_END = INNER_MSG_FORWARD_BEGIN + 20,

    // Emergency number message definition begin.
    INNER_MSG_ENMERGENCYNUMBER_BEGIN,
    // Emergency number message definition end.
    INNER_MSG_ENMERGENCYNUMBER_END = INNER_MSG_ENMERGENCYNUMBER_BEGIN + 20,

    // Feature code message definition begin.
    INNER_MSG_FEATURECODE_BEGIN,
    // Feature code message definition end.
    INNER_MSG_FEATURECODE_END = INNER_MSG_FEATURECODE_BEGIN + 20,

    // Feature sync message definition begin.
    INNER_MSG_FEATURESYNCMESSAGE_BEGIN,
    // Feature sync message definition end.
    INNER_MSG_FEATURESYNCMESSAGE_END = INNER_MSG_FEATURESYNCMESSAGE_BEGIN + 20,

    // Programmable key message definition begin.
    INNER_MSG_PROGRAMMABLEKEY_BEGIN,
    // Programmable key message definition end.
    INNER_MSG_PROGRAMMABLEKEY_END = INNER_MSG_PROGRAMMABLEKEY_BEGIN + 100,

    // Phone state message definition begin.
    INNER_MSG_PHONESTATE_BEGIN,
    // Phone state message definition end.
    INNER_MSG_PHONESTATE_END = INNER_MSG_PHONESTATE_BEGIN + 50,

    // Idle screen model message definition begin.
    INNER_MSG_IDELSCREENMODEL_BEGIN,
    // Idle screen model message definition end.
    INNER_MSG_IDELSCREENMODEL_END = INNER_MSG_IDELSCREENMODEL_BEGIN + 20,

    // Phone status message definition begin.
    INNER_MSG_PHONESTATUS_BEGIN,
    // Phone status message definition end.
    INNER_MSG_PHONESTATUS_END = INNER_MSG_PHONESTATUS_BEGIN + 20,

    // Call waiting message definition begin.
    INNER_MSG_CALLWAITING_BEGIN,
    // Call waiting message definition end.
    INNER_MSG_CALLWAITING_END = INNER_MSG_CALLWAITING_BEGIN + 20,

    // Intercom message definition begin.
    INNER_MSG_INTERCOM_BEGIN,
    // Intercom message definition end.
    INNER_MSG_INTERCOM_END = INNER_MSG_INTERCOM_BEGIN + 20,

    // Advanced call feature message definition begin.
    INNER_MSG_ADVANCED_CALL_FEATURE_BEGIN,
    // Advance call feature message definition end.
    INNER_MSG_ADVANCED_CALL_FEATURE_END = INNER_MSG_ADVANCED_CALL_FEATURE_BEGIN + 100,

    // BroadSoft message definition begin.
    INNER_MSG_BROADSOFT_BEGIN,
    // BroadSoft message definition end.
    INNER_MSG_BROADSOFT_END = INNER_MSG_BROADSOFT_BEGIN + 100,

    // Display message definition begin.
    INNER_MSG_DISPLAY_BEGIN,
    // Display message definition end.
    INNER_MSG_DISPLAY_END = INNER_MSG_DISPLAY_BEGIN + 20,

    // Video message definition begin.
    INNER_MSG_VIDEO_MESSAGE_BEGIN,
    // Video message definition end.
    INNER_MSG_VIDEO_MESSAGE_END = INNER_MSG_VIDEO_MESSAGE_BEGIN + 20,

    // Phone lock message definition begin.
    INNER_MSG_PHONE_LOCK_BEGIN,
    // Phone lock message definition end.
    INNER_MSG_PHONE_LOCK_END = INNER_MSG_PHONE_LOCK_BEGIN + 20,

    // Language message definition begin.
    INNER_MSG_LANGUAGE_BEGIN,
    // Language message definition end.
    INNER_MSG_LANGUAGE_END = INNER_MSG_LANGUAGE_BEGIN + 20,

    // 地址薄消息定义开始.
    INNER_MSG_DIRECTORY_MESSAGE_BEGIN,
    // 地址薄消息定义结束.
    INNER_MSG_DIRECTORY_MESSAGE_END = INNER_MSG_DIRECTORY_MESSAGE_BEGIN + 150,

    // 账号消息定义开始.
    INNER_MSG_ACCOUNT_MESSAGE_BEGIN,
    // 账号消息定义结束.
    INNER_MSG_ACCOUNT_MESSAGE_END = INNER_MSG_ACCOUNT_MESSAGE_BEGIN + 50,

    // Action URL/URI消息定义开始.
    INNER_MSG_ACTION_URL_MESSAGE_BEGIN,
    // Action URL/URI消息定义结束.
    INNER_MSG_ACTION_URL_MESSAGE_END = INNER_MSG_ACTION_URL_MESSAGE_BEGIN + 100,

    // CALLLOG消息定义开始.
    INNER_MSG_CALLLOG_MESSAGE_BEGIN,
    // CALLLOG消息定义结束.
    INNER_MSG_CALLLOG_MESSAGE_END = INNER_MSG_CALLLOG_MESSAGE_BEGIN + 100,

    // CallCompletion消息定义开始.
    INNER_MSG_CALLCOMPLETION_MESSAGE_BEGIN,
    // CallCompletion消息定义结束.
    INNER_MSG_CALLCOMPLETION_MESSAGE_END = INNER_MSG_CALLCOMPLETION_MESSAGE_BEGIN + 20,

    // autop弹出框消息定义开始
    INNER_MSG_AUTOPROVISION_MESSAGE_BEGIN,
    // autop弹出框消息定义结束.
    INNER_MSG_AUTOPROVISION_MESSAGE_END = INNER_MSG_AUTOPROVISION_MESSAGE_BEGIN + 10,

    // ACD消息定义开始
    INNER_MSG_ACD_MESSAGE_BEGIN,
    // ACD消息定义结束.
    INNER_MSG_ACD_MESSAGE_END = INNER_MSG_ACD_MESSAGE_BEGIN + 10,

    // ACD消息定义开始
    INNER_MSG_HOTELING_MESSAGE_BEGIN,
    // ACD消息定义结束.
    INNER_MSG_HOTELING_MESSAGE_END = INNER_MSG_HOTELING_MESSAGE_BEGIN + 10,

    //CLID消息定义开始
    INNER_MSG_CLID_MESSAGE_BEGIN,
    // CLID消息定义结束.
    INNER_MSG_CLID_MESSAGE_END = INNER_MSG_CLID_MESSAGE_BEGIN + 10,

    // Anywhere消息定义开始
    INNER_MSG_ANYWHERE_MESSAGE_BEGIN,
    // Anywhere消息定义结束.
    INNER_MSG_ANYWHERE_MESSAGE_END = INNER_MSG_ANYWHERE_MESSAGE_BEGIN + 20,

    //Remote Office消息定义开始
    INNER_MSG_RO_MESSAGE_BEGIN,
    //Remote Office消息定义结束.
    INNER_MSG_RO_MESSAGE_END = INNER_MSG_RO_MESSAGE_BEGIN + 10,

    //Simultaneous Ring Personal消息定义开始
    INNER_MSG_SRP_MESSAGE_BEGIN,
    //Simultaneous Ring Personal消息定义结束.
    INNER_MSG_SRP_MESSAGE_END = INNER_MSG_SRP_MESSAGE_BEGIN + 10,

    //Call Forward Not Reachable消息定义开始
    INNER_MSG_CFNR_MESSAGE_BEGIN,
    //Call Forward Not Reachable消息定义结束.
    INNER_MSG_CFNR_MESSAGE_END = INNER_MSG_CFNR_MESSAGE_BEGIN + 10,

    //Call Forward Not Reachable消息定义开始
    INNER_MSG_MBLT_MESSAGE_BEGIN,
    //Call Forward Not Reachable消息定义结束.
    INNER_MSG_MBLT_MESSAGE_END = INNER_MSG_MBLT_MESSAGE_BEGIN + 10,

    //Group Night Forward消息定义开始
    INNER_MSG_GNF_MESSAGE_BEGIN,
    //Group Night Forward消息定义结束.
    INNER_MSG_GNF_MESSAGE_END = INNER_MSG_GNF_MESSAGE_BEGIN + 10,

    INNER_MSG_POWER_LED_MESSAGE_BEGIN,
    INNER_MSG_POWER_LED_MESSAGE_END = INNER_MSG_POWER_LED_MESSAGE_BEGIN + 10,

    INNER_MSG_AUTHORITY_MESSAGE_BEGIN = INNER_MSG_POWER_LED_MESSAGE_END + 1,
    INNER_MSG_AUTHORITY_MESSAGE_END = INNER_MSG_AUTHORITY_MESSAGE_BEGIN + 10,

    INNER_MSG_BLUETOOTH_MESSAGE_BEGIN = INNER_MSG_AUTHORITY_MESSAGE_END + 1,
    INNER_MSG_BLUETOOTH_MESSAGE_END = INNER_MSG_BLUETOOTH_MESSAGE_BEGIN + 50,

    INNER_MSG_PRESENCE_MESSAGE_BEGIN,

    INNER_MSG_PRESENCE_MESSAGE_END = INNER_MSG_PRESENCE_MESSAGE_BEGIN + 20,

    // 进程退出前，收到某些信号，各模块dump info
    INNER_MSG_CATCH_SIG_TO_EXIT,

    INNER_MSG_POPUPBOX_MESSAGE_BEGIN,

    INNER_MSG_POPUPBOX_MESSAGE_END = INNER_MSG_POPUPBOX_MESSAGE_BEGIN + 50,

    // dsskey改变
    INNER_MSG_DSSKEY_MESSAGE_BEGIN,
    INNER_MSG_DSSKEY_MESSAGE_END = INNER_MSG_DSSKEY_MESSAGE_BEGIN + 10,

    // blflist数据更新消息
    INNER_MSG_BLFLIST_MESSAGE_BEGIN,
    INNER_MSG_BLFLIST_MESSAGE_END = INNER_MSG_BLFLIST_MESSAGE_BEGIN + 10,

    // blflist数据更新消息
    INNER_MSG_RTCP_MESSAGE_BEGIN,
    INNER_MSG_RTCP_MESSAGE_END = INNER_MSG_RTCP_MESSAGE_BEGIN + 10,

    // 背光灯消息
    INNER_MSG_BACKLIGHT_MESSAGE_BEGIN,
    INNER_MSG_BACKLIGHT_MESSAGE_END = INNER_MSG_BACKLIGHT_MESSAGE_BEGIN + 10,

    // multicast数据更新消息
    INNER_MSG_MULTICAST_MESSAGE_BEGIN,
    INNER_MSG_MULTICAST_MESSAGE_END = INNER_MSG_MULTICAST_MESSAGE_BEGIN + 10,

    // voice消息
    INNER_MSG_VOICE_MESSAGE_BEGIN,
    INNER_MSG_VOICE_MESSAGE_END = INNER_MSG_VOICE_MESSAGE_BEGIN + 10,

    // BLA消息
    INNER_MSG_BLA_MESSAGE_BEGIN,
    INNER_MSG_BLA_MESSAGE_END = INNER_MSG_BLA_MESSAGE_BEGIN + 10,

    // Talk消息
    INNER_MSG_TALK_MESSAGE_BEGIN,
    INNER_MSG_TALK_MESSAGE_END = INNER_MSG_TALK_MESSAGE_BEGIN + 100,

    // Edk消息
    INNER_MSG_EDK_MESSAGE_BEGIN,
    INNER_MSG_EDK_MESSAGE_END = INNER_MSG_EDK_MESSAGE_BEGIN + 10,

    // GetBalance消息
    INNER_MSG_GET_BALANCE_BEGIN,
    INNER_MSG_GET_BALANCE_END = INNER_MSG_GET_BALANCE_BEGIN + 10,

    // XSI Message
    INNER_MSG_XSI_MESSAGE_BEGIN,
    INNER_MSG_XSI_MESSAGE_END = INNER_MSG_XSI_MESSAGE_BEGIN + 20,

    // Wifi消息
    INNER_MSG_WIFI_MESSAGE_BEGIN,
    INNER_MSG_WIFI_MESSAGE_END = INNER_MSG_WIFI_MESSAGE_BEGIN + 30,

    // TestMode Message
    INNER_MSG_TESTMODE_MESSAGE_BEGIN,
    INNER_MSG_TESTMODE_MESSAGE_END = INNER_MSG_TESTMODE_MESSAGE_BEGIN + 10,

    // setting消息
    INNER_MSG_SETTING_MESSAGE_BEGIN,
    INNER_MSG_SETTING_MESSAGE_END = INNER_MSG_SETTING_MESSAGE_BEGIN + 20,

    INNER_MSG_HANDSETINFO_MESSAGE_BEGIN,
    INNER_MSG_HANDSETINFO_MESSAGE_END = INNER_MSG_HANDSETINFO_MESSAGE_BEGIN + 30,

    INNER_MSG_KEYPROCESSOR_MESSAGE_BEGIN,
    INNER_MSG_KEYPROCESSOR_MESSAGE_END = INNER_MSG_KEYPROCESSOR_MESSAGE_BEGIN + 10,

    INNER_MSG_LED_MESSAGE_BEGIN,
    INNER_MSG_LED_MESSAGE_END = INNER_MSG_LED_MESSAGE_BEGIN + 20,

    INNER_MSG_AUTOP_MESSAGE_BEGIN,
    INNER_MSG_AUTOP_MESSAGE_END = INNER_MSG_AUTOP_MESSAGE_BEGIN + 5,

    INNTER_MSG_CMDPROCESSOR_MESSAGE_BEGIN,
    INNTER_MSG_CMDPROCESSOR_MESSAGE_END = INNTER_MSG_CMDPROCESSOR_MESSAGE_BEGIN + 10,

    // 热插拔设备
    INNER_MSG_HOTPLUG_MESSAGE_BEGIN,
    INNER_MSG_HOTPLUG_MESSAGE_END = INNER_MSG_HOTPLUG_MESSAGE_BEGIN + 50,

    // Camera设备
    INNER_MSG_CAMERA_MESSAGE_BEGIN,
    INNER_MSG_CAMERA_MESSAGE_END = INNER_MSG_CAMERA_MESSAGE_BEGIN + 20,

    // Hdmi
    INNER_MSG_HDMI_MESSAGE_BEGIN,
    INNER_MSG_HDMI_MESSAGE_END = INNER_MSG_HDMI_MESSAGE_BEGIN + 20,

    // Camera设备
    INNER_MSG_MEDIA_MESSAGE_BEGIN,
    INNER_MSG_MEDIA_MESSAGE_END = INNER_MSG_MEDIA_MESSAGE_BEGIN + 20,

    // record消息
    INNER_MSG_RECORD_MESSAGE_BEGIN,
    INNER_MSG_RECORD_MESSAGE_END = INNER_MSG_RECORD_MESSAGE_BEGIN + 20,

    // record test消息
    INNER_MSG_RECORDTEST_MESSAGE_BEGIN,
    INNER_MSG_RECORDTEST_MESSAGE_END = INNER_MSG_RECORDTEST_MESSAGE_BEGIN + 20,

    INNER_MSG_GUI_DEBUG_BEGIN,
    INNER_MSG_GUI_DEBUG_END = INNER_MSG_GUI_DEBUG_BEGIN + 30,

    // Forward message definition begin.
    INNER_MSG_FORWORD_SYNC_BEGIN,
    // Forward message definition end.
    INNER_MSG_FORWORD_SYNC_END = INNER_MSG_FORWORD_SYNC_BEGIN + 20,

    //ping & traceroute
    INNER_MSG_DIAGNOTICS_BEGIN,
    INNER_MSG_DIAGNOTICS_END = INNER_MSG_DIAGNOTICS_BEGIN + 20,

    //节电模式消息
    INNER_MSG_POWERSAVING_MESSAGE_BEGIN,
    INNER_MSG_POWERSAVING_MESSAGE_END = INNER_MSG_POWERSAVING_MESSAGE_BEGIN + 10,

    INTER_MSG_DOOR_PHONE_MESSAGE_BEGIN,
    INTER_MSG_DOOR_PHONE_MESSAGE_END = INTER_MSG_DOOR_PHONE_MESSAGE_BEGIN + 20,

    // Forward message definition begin.
    PHONE_MESSAGE_FORWARD_BEGIN,
    // Forward message definition end.
    PHONE_MESSAGE_FORWARD_END = PHONE_MESSAGE_FORWARD_BEGIN + 20,

    // USB headset message define
    INNER_MSG_USBHEADSET_MESSAGE_BEGIN,
    INNER_MSG_USBHEADSET_MESSAGE_END = INNER_MSG_USBHEADSET_MESSAGE_BEGIN + 20,
    // PSTN消息
    INNER_MSG_PSTN_MESSAGE_BEGIN,
    INNER_MSG_PSTN_MESSAGE_END = INNER_MSG_PSTN_MESSAGE_BEGIN + 10,

    INNER_MSG_FLEXIBLE_MESSAGE_BEGIN,
    INNER_MSG_FLEXIBLE_MESSAGE_END = INNER_MSG_FLEXIBLE_MESSAGE_BEGIN + 10,

    // datetime消息
    INNER_MSG_DATE_TIME_BEGIN,
    INNER_MSG_DATE_TIME_END = INNER_MSG_DATE_TIME_BEGIN + 10,

    // color exp & LCD exp
    INNER_MSG_EXP_MESSAGE_BEGIN,
    INNER_MSG_EXP_MESSAGE_END = INNER_MSG_EXP_MESSAGE_BEGIN + 20,

    // exp scan thread
    INNER_MSG_EXP_SCANNER_MESSAGE_BEGIN,
    INNER_MSG_EXP_SCANNER_MESSAGE_END = INNER_MSG_EXP_SCANNER_MESSAGE_BEGIN + 5,
    //Metaswitch
    INNER_MSG_MTSW_ACD_MESSAGE_BEGIN,
    INNER_MSG_MTSW_ACD_MESSAGE_END = INNER_MSG_MTSW_ACD_MESSAGE_BEGIN + 10,

    INNER_MSG_MTSW_MESSAGE_BEGIN,
    INNER_MSG_MTSW_MESSAGE_END = INNER_MSG_MTSW_MESSAGE_BEGIN + 10,

    INNER_MSG_E911_MESSAGE_BEGIN,
    INNER_MSG_E911_MESSAGE_END = INNER_MSG_E911_MESSAGE_BEGIN + 10,

    // image消息
    INTER_MSG_IMAGE_MESSAGE_BEGIN,
    INTER_MSG_IMAGE_MESSAGE_END = INTER_MSG_IMAGE_MESSAGE_BEGIN + 10,

    //autotestmgr
    INNER_MSG_AUTO_TEST_MESSAGE_BEGIN,
    INNER_MSG_AUTO_TEST_MESSAGE_END = INNER_MSG_AUTO_TEST_MESSAGE_BEGIN + 20,

    INTER_MSG_USER_MODE_MESSAGE_BEGIN,
    INTER_MSG_USER_MODE_MESSAGE_END = INTER_MSG_USER_MODE_MESSAGE_BEGIN + 10,

    INNER_MSG_LAST,
};

#endif // __INNER_MSG_DEFINE_H__
